In [143]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cpu


### Introduction To Tensors
#### Creating Tensors

In [144]:
# scaler
scalar = torch.tensor(16)
scalar

tensor(16)

In [145]:
scalar.ndim

0

In [146]:
scalar.item()

16

In [147]:
# Vector
vector = torch.tensor([16, 16])
vector

tensor([16, 16])

In [148]:
vector.ndim

1

In [149]:
vector.shape

torch.Size([2])

In [150]:
 # MATRIX
 MATRIX = torch.tensor([[7, 8],
                        [9, 10]])
 MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [151]:
MATRIX.ndim

2

In [152]:
MATRIX[1]

tensor([ 9, 10])

In [153]:
MATRIX[0]

tensor([7, 8])

In [154]:
MATRIX.shape

torch.Size([2, 2])

In [155]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [156]:
TENSOR.ndim

3

In [157]:
TENSOR.shape

torch.Size([1, 3, 3])

In [158]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [159]:
TENSOR2 = torch.tensor ([[[[[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9],
               [10, 11, 12]]]]]])
TENSOR2

tensor([[[[[[ 1,  2,  3],
            [ 4,  5,  6],
            [ 7,  8,  9],
            [10, 11, 12]]]]]])

In [160]:
TENSOR2.ndim

6

In [161]:
TENSOR2.shape

torch.Size([1, 1, 1, 1, 4, 3])

In [162]:
TENSOR2[0]

tensor([[[[[ 1,  2,  3],
           [ 4,  5,  6],
           [ 7,  8,  9],
           [10, 11, 12]]]]])

In [163]:
TENSOR3 = torch.tensor ([[[[[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9],
               [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18],
                [19, 20, 21],
                [22,23, 24]]]]]])
TENSOR3

tensor([[[[[[ 1,  2,  3],
            [ 4,  5,  6],
            [ 7,  8,  9],
            [10, 11, 12]],

           [[13, 14, 15],
            [16, 17, 18],
            [19, 20, 21],
            [22, 23, 24]]]]]])

In [164]:
TENSOR3.ndim

6

In [165]:
TENSOR.shape

torch.Size([1, 3, 3])

In [166]:
TENSOR3[0]

tensor([[[[[ 1,  2,  3],
           [ 4,  5,  6],
           [ 7,  8,  9],
           [10, 11, 12]],

          [[13, 14, 15],
           [16, 17, 18],
           [19, 20, 21],
           [22, 23, 24]]]]])

In [167]:
TENSOR4 = torch.tensor ([[[[[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9],
               [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18],
                [19, 20, 21],
                [22,23, 24]],
                [[31,32, 33],
               [34, 35, 36],
               [37, 38, 39],
               [103, 113, 123]],
               [[136, 146, 156],
                [166, 176, 186],
                [196, 206, 216],
                [226,236, 246]]]]]])
TENSOR4

tensor([[[[[[  1,   2,   3],
            [  4,   5,   6],
            [  7,   8,   9],
            [ 10,  11,  12]],

           [[ 13,  14,  15],
            [ 16,  17,  18],
            [ 19,  20,  21],
            [ 22,  23,  24]],

           [[ 31,  32,  33],
            [ 34,  35,  36],
            [ 37,  38,  39],
            [103, 113, 123]],

           [[136, 146, 156],
            [166, 176, 186],
            [196, 206, 216],
            [226, 236, 246]]]]]])

In [168]:
TENSOR4.ndim

6

In [169]:
TENSOR4.shape

torch.Size([1, 1, 1, 4, 4, 3])

In [170]:
TENSOR4[0]

tensor([[[[[  1,   2,   3],
           [  4,   5,   6],
           [  7,   8,   9],
           [ 10,  11,  12]],

          [[ 13,  14,  15],
           [ 16,  17,  18],
           [ 19,  20,  21],
           [ 22,  23,  24]],

          [[ 31,  32,  33],
           [ 34,  35,  36],
           [ 37,  38,  39],
           [103, 113, 123]],

          [[136, 146, 156],
           [166, 176, 186],
           [196, 206, 216],
           [226, 236, 246]]]]])

In [171]:
TENSOR5 = torch.tensor ([[[[[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9],
               [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18],
                [19, 20, 21],
                [22,23, 24]],
                [[31,32, 33],
               [34, 35, 36],
               [37, 38, 39],
               [103, 113, 123]],
               [[136, 146, 156],
                [166, 176, 186],
                [196, 206, 216],
                [226,236, 246]],
                [[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9],
               [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18],
                [19, 20, 21],
                [22,23, 24]],
                [[31,32, 33],
               [34, 35, 36],
               [37, 38, 39],
               [103, 113, 123]],
               [[136, 146, 156],
                [166, 176, 186],
                [196, 206, 216],
                [226,236, 246]]]]]])
TENSOR5

tensor([[[[[[  1,   2,   3],
            [  4,   5,   6],
            [  7,   8,   9],
            [ 10,  11,  12]],

           [[ 13,  14,  15],
            [ 16,  17,  18],
            [ 19,  20,  21],
            [ 22,  23,  24]],

           [[ 31,  32,  33],
            [ 34,  35,  36],
            [ 37,  38,  39],
            [103, 113, 123]],

           [[136, 146, 156],
            [166, 176, 186],
            [196, 206, 216],
            [226, 236, 246]],

           [[  1,   2,   3],
            [  4,   5,   6],
            [  7,   8,   9],
            [ 10,  11,  12]],

           [[ 13,  14,  15],
            [ 16,  17,  18],
            [ 19,  20,  21],
            [ 22,  23,  24]],

           [[ 31,  32,  33],
            [ 34,  35,  36],
            [ 37,  38,  39],
            [103, 113, 123]],

           [[136, 146, 156],
            [166, 176, 186],
            [196, 206, 216],
            [226, 236, 246]]]]]])

In [172]:
TENSOR5.ndim

6

In [173]:
TENSOR5.shape

torch.Size([1, 1, 1, 8, 4, 3])

In [174]:
TENSOR5[0]

tensor([[[[[  1,   2,   3],
           [  4,   5,   6],
           [  7,   8,   9],
           [ 10,  11,  12]],

          [[ 13,  14,  15],
           [ 16,  17,  18],
           [ 19,  20,  21],
           [ 22,  23,  24]],

          [[ 31,  32,  33],
           [ 34,  35,  36],
           [ 37,  38,  39],
           [103, 113, 123]],

          [[136, 146, 156],
           [166, 176, 186],
           [196, 206, 216],
           [226, 236, 246]],

          [[  1,   2,   3],
           [  4,   5,   6],
           [  7,   8,   9],
           [ 10,  11,  12]],

          [[ 13,  14,  15],
           [ 16,  17,  18],
           [ 19,  20,  21],
           [ 22,  23,  24]],

          [[ 31,  32,  33],
           [ 34,  35,  36],
           [ 37,  38,  39],
           [103, 113, 123]],

          [[136, 146, 156],
           [166, 176, 186],
           [196, 206, 216],
           [226, 236, 246]]]]])

In [175]:
# Create a random tensor of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.4675, 0.5631, 0.8202, 0.6948],
        [0.5926, 0.5824, 0.2176, 0.7675],
        [0.2747, 0.8498, 0.8566, 0.0796]])

In [176]:
random_tensor.ndim

2

In [177]:
random_tensor2 = torch.rand(1, 1, 8, 4, 3)
random_tensor2

tensor([[[[[7.1556e-01, 2.5887e-01, 3.3311e-01],
           [6.7958e-01, 3.6453e-01, 3.6104e-01],
           [2.8379e-01, 5.0644e-02, 8.3821e-01],
           [4.2233e-01, 7.7037e-02, 6.7386e-02]],

          [[1.5228e-01, 1.1035e-01, 1.3420e-01],
           [3.0834e-01, 2.5448e-01, 1.1810e-02],
           [5.4294e-01, 3.5196e-01, 7.0083e-01],
           [3.3356e-01, 2.3407e-01, 7.5065e-01]],

          [[5.0726e-01, 1.0554e-01, 3.7096e-01],
           [1.6145e-01, 6.7448e-02, 6.8478e-01],
           [3.1851e-01, 7.6571e-01, 6.5386e-01],
           [6.5303e-01, 6.0925e-01, 2.5131e-01]],

          [[6.7789e-01, 8.4930e-01, 8.1834e-01],
           [6.8854e-01, 1.9631e-01, 4.8651e-01],
           [9.5451e-01, 8.8844e-01, 9.4046e-02],
           [4.2358e-01, 9.3727e-01, 7.2995e-01]],

          [[1.5882e-01, 7.5489e-01, 5.5902e-01],
           [8.2565e-01, 9.4525e-01, 3.8387e-01],
           [6.6554e-01, 9.2225e-01, 2.2795e-01],
           [1.1015e-04, 9.5567e-01, 3.2449e-01]],

          

In [178]:
random_tensor2.ndim

5

In [179]:
random_tensor2.shape

torch.Size([1, 1, 8, 4, 3])

In [180]:
random_tensor2[0]

tensor([[[[7.1556e-01, 2.5887e-01, 3.3311e-01],
          [6.7958e-01, 3.6453e-01, 3.6104e-01],
          [2.8379e-01, 5.0644e-02, 8.3821e-01],
          [4.2233e-01, 7.7037e-02, 6.7386e-02]],

         [[1.5228e-01, 1.1035e-01, 1.3420e-01],
          [3.0834e-01, 2.5448e-01, 1.1810e-02],
          [5.4294e-01, 3.5196e-01, 7.0083e-01],
          [3.3356e-01, 2.3407e-01, 7.5065e-01]],

         [[5.0726e-01, 1.0554e-01, 3.7096e-01],
          [1.6145e-01, 6.7448e-02, 6.8478e-01],
          [3.1851e-01, 7.6571e-01, 6.5386e-01],
          [6.5303e-01, 6.0925e-01, 2.5131e-01]],

         [[6.7789e-01, 8.4930e-01, 8.1834e-01],
          [6.8854e-01, 1.9631e-01, 4.8651e-01],
          [9.5451e-01, 8.8844e-01, 9.4046e-02],
          [4.2358e-01, 9.3727e-01, 7.2995e-01]],

         [[1.5882e-01, 7.5489e-01, 5.5902e-01],
          [8.2565e-01, 9.4525e-01, 3.8387e-01],
          [6.6554e-01, 9.2225e-01, 2.2795e-01],
          [1.1015e-04, 9.5567e-01, 3.2449e-01]],

         [[9.0116e-01, 7.3942e

In [181]:
random_tensor3 = torch.rand(3, 2, 8, 4, 3)
random_tensor3

tensor([[[[[0.2453, 0.3085, 0.1625],
           [0.3531, 0.5263, 0.6273],
           [0.6609, 0.6507, 0.3415],
           [0.2836, 0.6407, 0.8131]],

          [[0.8211, 0.7479, 0.2545],
           [0.3897, 0.5980, 0.8053],
           [0.9200, 0.7424, 0.3126],
           [0.7556, 0.2427, 0.8790]],

          [[0.8110, 0.6163, 0.0433],
           [0.2652, 0.2516, 0.1982],
           [0.8782, 0.2206, 0.9863],
           [0.6014, 0.3604, 0.1877]],

          [[0.9388, 0.3685, 0.4638],
           [0.6945, 0.9525, 0.2421],
           [0.0274, 0.0164, 0.0840],
           [0.4883, 0.3420, 0.7411]],

          [[0.9664, 0.7336, 0.0591],
           [0.3568, 0.2757, 0.6034],
           [0.5418, 0.0073, 0.2613],
           [0.8483, 0.9516, 0.8216]],

          [[0.9891, 0.2896, 0.9745],
           [0.7853, 0.3794, 0.7450],
           [0.9669, 0.6595, 0.5932],
           [0.5718, 0.3462, 0.1077]],

          [[0.0699, 0.1798, 0.1534],
           [0.6272, 0.2086, 0.9416],
           [0.6266, 0.0038

In [182]:
random_tensor3.ndim

5

In [183]:
random_tensor3[2]

tensor([[[[0.6618, 0.8640, 0.9343],
          [0.0556, 0.5725, 0.2087],
          [0.4895, 0.9529, 0.0211],
          [0.8154, 0.5359, 0.5089]],

         [[0.7325, 0.6450, 0.6795],
          [0.2868, 0.4610, 0.2448],
          [0.7154, 0.1954, 0.3876],
          [0.4123, 0.6986, 0.3385]],

         [[0.5852, 0.8993, 0.8579],
          [0.3160, 0.3630, 0.1769],
          [0.0309, 0.3603, 0.3061],
          [0.9377, 0.7673, 0.4010]],

         [[0.2327, 0.3462, 0.6235],
          [0.7835, 0.9492, 0.4267],
          [0.2457, 0.1144, 0.7372],
          [0.6942, 0.8731, 0.6519]],

         [[0.6958, 0.0103, 0.9920],
          [0.5820, 0.3931, 0.1290],
          [0.1334, 0.5007, 0.5772],
          [0.8857, 0.2292, 0.2687]],

         [[0.9634, 0.2945, 0.4128],
          [0.7569, 0.9957, 0.1702],
          [0.3585, 0.1409, 0.0877],
          [0.8704, 0.9503, 0.1852]],

         [[0.4843, 0.0280, 0.7216],
          [0.9497, 0.0689, 0.0104],
          [0.4120, 0.7573, 0.2968],
          [0.566

In [184]:
# Creayte a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size= (256, 256, 3)) # height, width, colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([256, 256, 3]), 3)

In [185]:
image_shape_tensor = torch.rand(size= (3, 256, 256)) # colour channel, height, width
image_shape_tensor

tensor([[[0.5289, 0.6730, 0.8161,  ..., 0.9646, 0.9871, 0.1126],
         [0.3168, 0.3045, 0.7190,  ..., 0.8592, 0.8901, 0.6572],
         [0.8090, 0.7897, 0.0799,  ..., 0.5109, 0.5310, 0.9482],
         ...,
         [0.1104, 0.0844, 0.4510,  ..., 0.1305, 0.0566, 0.8065],
         [0.8454, 0.7591, 0.7870,  ..., 0.3846, 0.8012, 0.2419],
         [0.0113, 0.0309, 0.2584,  ..., 0.8291, 0.6659, 0.0604]],

        [[0.3510, 0.3108, 0.5430,  ..., 0.5541, 0.8905, 0.2005],
         [0.0124, 0.0751, 0.9455,  ..., 0.5218, 0.6984, 0.2289],
         [0.5440, 0.8191, 0.9712,  ..., 0.8458, 0.7054, 0.5017],
         ...,
         [0.6228, 0.7369, 0.6118,  ..., 0.0075, 0.6573, 0.3656],
         [0.0854, 0.4949, 0.1406,  ..., 0.1805, 0.7888, 0.5982],
         [0.0569, 0.8974, 0.9293,  ..., 0.7707, 0.8843, 0.5041]],

        [[0.3368, 0.5372, 0.7587,  ..., 0.9866, 0.2359, 0.7287],
         [0.4606, 0.2766, 0.2921,  ..., 0.4287, 0.1804, 0.7441],
         [0.5057, 0.7580, 0.4917,  ..., 0.0124, 0.1020, 0.

In [186]:
image_shape_tensor.shape, image_shape_tensor.ndim

(torch.Size([3, 256, 256]), 3)

### Zeros and Ones

In [187]:
zeros = torch.zeros(size=(4, 6))
zeros

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [188]:
zeros.dtype

torch.float32

In [189]:
ones = torch.ones(size=(4, 6))
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [190]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [191]:
# Use torch.range()
torch.range(0,16)

/tmp/ipykernel_1290/3854708265.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,16)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16.])

In [192]:
torch.arange(0, 16)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [193]:
one_to_hundred = torch.arange(start=0, end=100, step=10)
one_to_hundred

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [194]:
one_to_thousand = torch.arange(start= 2, end = 1000, step = 16)
one_to_thousand

tensor([  2,  18,  34,  50,  66,  82,  98, 114, 130, 146, 162, 178, 194, 210,
        226, 242, 258, 274, 290, 306, 322, 338, 354, 370, 386, 402, 418, 434,
        450, 466, 482, 498, 514, 530, 546, 562, 578, 594, 610, 626, 642, 658,
        674, 690, 706, 722, 738, 754, 770, 786, 802, 818, 834, 850, 866, 882,
        898, 914, 930, 946, 962, 978, 994])

In [195]:
# Creating tensors like
one_to_thousand_like = torch.zeros_like(input=one_to_thousand)
one_to_thousand_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [196]:
like_hundred = torch.ones_like(input=one_to_hundred)
like_hundred

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [197]:
like_thousand = torch.rand_like(one_to_thousand, dtype=torch.float32 )
like_thousand

tensor([0.9016, 0.8499, 0.3776, 0.7396, 0.6362, 0.4614, 0.8138, 0.6285, 0.3016,
        0.7464, 0.8239, 0.6931, 0.4059, 0.9691, 0.6769, 0.1418, 0.4282, 0.6894,
        0.4645, 0.5210, 0.5156, 0.2088, 0.2019, 0.7265, 0.0075, 0.5413, 0.7010,
        0.5852, 0.0770, 0.9910, 0.3065, 0.5164, 0.5792, 0.7528, 0.7983, 0.7861,
        0.3638, 0.1174, 0.8347, 0.7582, 0.3281, 0.9663, 0.8505, 0.2719, 0.8193,
        0.5477, 0.5700, 0.7075, 0.7888, 0.1840, 0.8375, 0.1541, 0.9751, 0.8415,
        0.7028, 0.0936, 0.9408, 0.3274, 0.1791, 0.9501, 0.3261, 0.8926, 0.7825])

In [198]:
like_hundred2 = torch.rand_like(one_to_hundred, dtype=torch.float32)
like_hundred2

tensor([0.1573, 0.3790, 0.4337, 0.5314, 0.8007, 0.2687, 0.0300, 0.3520, 0.6816,
        0.9318])

## Tensor Datatypes


In [199]:
# Float 32 tensor
# Float 32 is default datatype in PyTorch
float_32 = torch.tensor([.4, .5, .6], dtype=None)
float_32

tensor([0.4000, 0.5000, 0.6000])

In [200]:
import sys
float_32_tensor = torch.tensor([1.0, 6.0, 16.0], dtype=None)
sys.stdout.write(str(float_32_tensor) + '\n' + str(float_32_tensor.dtype)) #37 is the character count for standard output

tensor([ 1.,  6., 16.])
torch.float32

37

In [201]:
float_32_tensor = torch.tensor([1.0, 6.0, 16.0], dtype=None)
float_32_tensor.shape, float_32_tensor.ndim, float_32_tensor.dtype

(torch.Size([3]), 1, torch.float32)

In [202]:
float_32_tensor = torch.tensor([1.0, 6.0, 16.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([ 1.,  6., 16.])

In [203]:
float_16_tensor = torch.tensor([1.0, 6.0, 16.0],
                               dtype=torch.float16,
                               device=None,
                               requires_grad=False)
float_16_tensor

tensor([ 1.,  6., 16.], dtype=torch.float16)

In [204]:
float_16_tensor.dtype

torch.float16

In [205]:
float_16_tensor = torch.tensor([1.0, 6.0, 16.0],
                               dtype=torch.float16,
                               device="cpu",
                               requires_grad=False)
float_16_tensor.device

device(type='cpu')

In [206]:
float_16_tensor2 = float_32_tensor.type(torch.float16)
float_16_tensor2.dtype

torch.float16

In [207]:
float_16_tensor * float_32_tensor

tensor([  1.,  36., 256.])

In [208]:
int_32_tensor = torch.rand([1, 3])
int_32_tensor

tensor([[0.4482, 0.3576, 0.8493]])

In [209]:
float_32_tensor * int_32_tensor

tensor([[ 0.4482,  2.1454, 13.5883]])

In [210]:
long_64_tensor = torch.tensor([1, 6, 16], dtype=torch.long)
long_64_tensor

tensor([ 1,  6, 16])

In [211]:
float_32_tensor * long_64_tensor

tensor([  1.,  36., 256.])

In [212]:
kinda_tensor = torch.rand([6,6])
print(kinda_tensor)
print(f"Kinda Tensor's datatype:{kinda_tensor.dtype}") #attribute
print(f"Kinda Tensor's shape: {kinda_tensor.shape}") #attribute
print(f"Kinda Tensor's device: {kinda_tensor.device}") #attribute
print(f"Kinda Tensors size: {kinda_tensor.size()}") #size is a function

tensor([[0.5838, 0.4256, 0.8518, 0.6607, 0.1766, 0.7560],
        [0.2800, 0.9075, 0.6431, 0.3556, 0.5198, 0.7600],
        [0.4337, 0.2615, 0.7390, 0.6473, 0.4692, 0.3846],
        [0.5669, 0.1959, 0.4363, 0.9140, 0.6614, 0.0941],
        [0.9934, 0.7157, 0.0472, 0.4605, 0.2123, 0.0764],
        [0.4720, 0.1193, 0.2051, 0.2489, 0.4343, 0.7336]])
Kinda Tensor's datatype:torch.float32
Kinda Tensor's shape: torch.Size([6, 6])
Kinda Tensor's device: cpu
Kinda Tensors size: torch.Size([6, 6])


In [213]:
device = "cuda" if torch.cuda.is_available() else "cpu"
meh_tensor = torch.rand([6,6], dtype=torch.float16, device=device)
print(meh_tensor)
print(f"Meh Tensor's datatype:{meh_tensor.dtype}") #attribute
print(f"Meh Tensor's shape: {meh_tensor.shape}") #attribute
print(f"Meh Tensor's device: {meh_tensor.device}") #attribute
print(f"Meh Tensors size: {meh_tensor.size()}") #size is a function

tensor([[0.0200, 0.6401, 0.5137, 0.0620, 0.5161, 0.6870],
        [0.1396, 0.5542, 0.9419, 0.7661, 0.4062, 0.5264],
        [0.5703, 0.5386, 0.9448, 0.6284, 0.2163, 0.9336],
        [0.4268, 0.3188, 0.7690, 0.2354, 0.1455, 0.3940],
        [0.4033, 0.1523, 0.8418, 0.3491, 0.4595, 0.1797],
        [0.2622, 0.4160, 0.3379, 0.2432, 0.5815, 0.0098]], dtype=torch.float16)
Meh Tensor's datatype:torch.float16
Meh Tensor's shape: torch.Size([6, 6])
Meh Tensor's device: cpu
Meh Tensors size: torch.Size([6, 6])


## Manipulating Tensors

In [214]:
tensor1 = torch.tensor([100, 200, 300])
tensor1 + 100

tensor([200, 300, 400])

In [215]:
tensor1 - 100

tensor([  0, 100, 200])

In [216]:
tensor1 * 100

tensor([10000, 20000, 30000])

In [217]:
tensor1 / 100

tensor([1., 2., 3.])

### PyTorch in-build functions

In [218]:
torch.add(tensor1, 100)

tensor([200, 300, 400])

In [219]:
torch.sub(tensor1, 100)

tensor([  0, 100, 200])

In [220]:
torch.mul(tensor1, 100)

tensor([10000, 20000, 30000])

In [221]:
torch.div(tensor1, 100)

tensor([1., 2., 3.])

In [222]:
# Element wise multiplication
print(tensor1, "*", tensor1)
print(f"Multiplication equals:{tensor1 * tensor1}")

tensor([100, 200, 300]) * tensor([100, 200, 300])
Multiplication equals:tensor([10000, 40000, 90000])


In [223]:
torch.matmul(tensor1, tensor1) #This is just the addition of the element wise products

tensor(140000)

## This ChatGPT chat show why the below to code shows different outcomes?
- https://chatgpt.com/share/68911a9a-a8e8-8009-bbbc-cdfece7c3167

In [224]:
%%time
value = 0
for i in range (len(tensor1)):
  value += tensor1[i] * tensor1[i]
print(value)

tensor(140000)
CPU times: user 1.12 ms, sys: 13 µs, total: 1.13 ms
Wall time: 956 µs


In [225]:
%%time
torch.matmul(tensor1, tensor1)

CPU times: user 222 µs, sys: 25 µs, total: 247 µs
Wall time: 203 µs


tensor(140000)

### One of the most common error in deep learning: shape errors (I know right!!!🙂)



#### 1. Inner Dimension must match:
* `(6,4) @ (6,4)` won't work
* `(4,6) @ (6,4)` will work
* `(6,4) @ (4,6)` will work


In [226]:
torch.matmul(torch.rand(4,6), torch.rand(6, 4))

tensor([[2.1608, 1.5837, 1.4692, 1.4064],
        [0.9258, 0.5696, 0.5674, 0.7000],
        [2.0457, 1.6729, 1.9738, 1.6594],
        [1.7846, 1.1211, 1.2854, 1.5454]])

#### 2. The resulting matrix has the shape of the **outer dimensions**:
* `(4,6) @ (6,4)` shapes -> (4,4)
* `(6,4) @ (4,6)` shapes -> (6,6)
* `(6,3) @ (3,4)` shapes -> (3,4)

In [227]:
torch.matmul(torch.rand(6, 4), torch.rand(4, 6))

tensor([[0.4350, 0.4714, 0.3772, 0.6058, 0.6087, 0.6264],
        [0.7787, 1.0687, 0.8024, 0.8716, 1.4400, 1.3705],
        [0.4676, 0.5390, 0.3546, 0.6098, 0.6161, 0.5544],
        [0.7591, 1.0993, 0.6262, 1.0884, 1.2478, 0.9313],
        [0.5047, 0.7776, 0.5610, 0.5056, 1.0563, 0.9631],
        [0.6454, 1.0392, 0.4823, 0.5415, 1.0878, 0.7021]])

In [228]:
torch.matmul(torch.rand(6, 4), torch.rand(4, 3))

tensor([[1.0765, 0.5722, 0.7830],
        [1.3408, 0.6728, 1.0853],
        [0.3909, 0.5307, 0.4710],
        [0.7105, 0.3908, 0.5946],
        [1.3781, 0.7383, 1.0631],
        [1.1649, 0.5714, 0.7496]])

### To fix our tensor shapr issues, we can manipulate the shape of one of our tensors using **Transpose**.

### A **transpose** switches the axes or dimensions of a given tensor.

In [229]:
tensorA = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
tensorB = torch. tensor([[11, 12],
                         [13, 14],
                         [15, 16]])
tensorA, tensorB

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor([[11, 12],
         [13, 14],
         [15, 16]]))

In [230]:
tensorA.T #Transpose of tensorA
tensorB.T #Tnanspose of tensorB

tensorA.T, tensorB.T

(tensor([[1, 3, 5],
         [2, 4, 6]]),
 tensor([[11, 13, 15],
         [12, 14, 16]]))

In [231]:
tensorA.shape, tensorB.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [232]:
tensorA.T.shape, tensorB.T.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [233]:
tensorA * tensorB # This is working because it is element wise multiplication

tensor([[11, 24],
        [39, 56],
        [75, 96]])

In [234]:
##torch.mm(tensorA, tensorB) <- This won't work for matrix multiplication
torch.mm(tensorA, tensorB.T) # mm = matmul

tensor([[ 35,  41,  47],
        [ 81,  95, 109],
        [127, 149, 171]])

In [235]:
torch.mm(tensorA, tensorB.T).shape  ## As of rule 2 for matrix multiplication

torch.Size([3, 3])

In [236]:
# The matrix multiplication operation works when tensorB is transposed
print(f"Original shapes: tensorA = {tensorA.shape}, tensorB = {tensorB.shape}")
print(f"New shapes: tensorA = {tensorA.shape} (same shape as above), tensorB.T = {tensorB.T.shape}")
print(f"Multiplying: {tensorA.shape} @ {tensorB.T.shape} <- inner dimensions must match")
print("Output: \n")
output = torch.mm(tensorA, tensorB.T)
print(output)
print(f"\nOutput shaper: {output.shape}")

Original shapes: tensorA = torch.Size([3, 2]), tensorB = torch.Size([3, 2])
New shapes: tensorA = torch.Size([3, 2]) (same shape as above), tensorB.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output: 

tensor([[ 35,  41,  47],
        [ 81,  95, 109],
        [127, 149, 171]])

Output shaper: torch.Size([3, 3])


## Tensor Aggregation
### Finding the min, max, mean, sum etc

In [237]:
# Create a tensor
x = torch.arange (0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [238]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [239]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [240]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()
 # WE needed to change datatype here because mean does not work on Long datatype.
 # It can only work on a tensor of floating point or a complex datatype.

(tensor(45.), tensor(45.))

In [241]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional mean and max

In [242]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [243]:
x.argmin()

tensor(0)

In [244]:
x[0]

tensor(0)

In [245]:
# Find the position in tensorthat has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs.
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [246]:
x.argmin()

tensor(0)

In [247]:
x[0]

tensor(1)

In [248]:
# Max value in tensor using argmax
x.argmax()

tensor(9)

In [249]:
y = torch.arange(-100, 1, 10)
y

tensor([-100,  -90,  -80,  -70,  -60,  -50,  -40,  -30,  -20,  -10,    0])

In [250]:
y.argmin()

tensor(0)

In [251]:
y[0]

tensor(-100)

In [252]:
y.argmax()

tensor(10)

In [253]:
y[9]

tensor(-10)

## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - Reshapes an input tensor to a defined shape.
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack).
* Squeeze - Removes all `1` dimensions from a tensor.
* Unsqueeze - Add a `1` dimension to a target tensor. * Permute - Return a view of the input with dimensions permuted (swapped) in a certain way.

In [254]:
 import torch
 x = torch.arange(1., 10.)
 x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [255]:
# Add an extra dimension
x_reshape = x.reshape(1, 9)
x_reshape, x_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [256]:
x_reshape = x.reshape(9, 1)
x_reshape, x_reshape.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [257]:
x_reshape = x.reshape(1, 9)
x_reshape

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [258]:
 y = torch.arange(1., 13.)
 y, y.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [259]:
y_reshape = y.reshape(3,4)
y_reshape, y_reshape.shape

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [260]:
# Change the view
z = y.view(1,12)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [261]:
z= y.view(12,1)
z, z.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.],
         [11.],
         [12.]]),
 torch.Size([12, 1]))

In [262]:
# Changing z changes y because the view of the tensor is the same memory as the original input
z[:, 0] = 6
z, y

(tensor([[6.],
         [6.],
         [6.],
         [6.],
         [6.],
         [6.],
         [6.],
         [6.],
         [6.],
         [6.],
         [6.],
         [6.]]),
 tensor([6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]))

In [263]:
z = y.view(3,4)
z

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])

In [264]:
 y = torch.arange(1., 13.)
 y, y.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [265]:
z = y.view(1, 12)
z

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [266]:
z [:, 0] = 6
z, y

(tensor([[ 6.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 6.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [267]:
## Stack tensors on top of each other
x_stacked = torch.stack([y, y, y, y], dim = 0) # We can't use other dimensions here because origial tensor is not compatiblr
x_stacked

tensor([[ 6.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 6.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 6.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 6.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [268]:
# But we can use 1
y_stacked = torch.stack([y, y, y, y, y, y], dim=1)
y_stacked

tensor([[ 6.,  6.,  6.,  6.,  6.,  6.],
        [ 2.,  2.,  2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.,  9.,  9.],
        [10., 10., 10., 10., 10., 10.],
        [11., 11., 11., 11., 11., 11.],
        [12., 12., 12., 12., 12., 12.]])

## Squeez and Unsqueez

In [269]:
x = torch.zeros(2,1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [270]:
y = torch.squeeze(x) # squeez removes all 1 dimensions
y.size()

torch.Size([2, 2, 2])

In [271]:
y = torch.squeeze(x, 0) # remov
y.size()

torch.Size([2, 1, 2, 1, 2])

In [272]:
y = torch.squeeze(x, 1)
y.size()

torch.Size([2, 2, 1, 2])

In [273]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous Tensor:{x_reshape}")
print(f"Previous Shape:{x_reshape.shape}")

#Remove extra Dimensions from x_reshape
x_squeezed = x_reshape.squeeze()
print(f"\nNew Tensor: {x_squeezed}")
print(f"\nNew Shape: {x_squeezed.shape}")

Previous Tensor:tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous Shape:torch.Size([1, 9])

New Tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

New Shape: torch.Size([9])


In [274]:
x_reshape

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [275]:
x_reshape.shape

torch.Size([1, 9])

In [276]:
x_reshape.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [277]:
x_reshape.squeeze().shape

torch.Size([9])

In [278]:
# torch.unsqueeze() - adds a single dimensions to a target tensor
print(f"Previous Tensor:{x_squeezed}")
print(f"Previous Shape:{x_squeezed.shape}")

#Remove extra Dimensions from x_reshape
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew Tensor: {x_unsqueezed}")
print(f"\nNew Shape: {x_unsqueezed.shape}")

Previous Tensor:tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous Shape:torch.Size([9])

New Tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

New Shape: torch.Size([1, 9])


In [279]:
# torch.unsqueeze() - adds a single dimensions to a target tensor
print(f"Previous Tensor:{x_unsqueezed}")
print(f"Previous Shape:{x_unsqueezed.shape}")

#Remove extra Dimensions from x_reshape
x_unsqueezed2 = x_unsqueezed.unsqueeze(dim=1)
print(f"\nNew Tensor: {x_unsqueezed2}")
print(f"\nNew Shape: {x_unsqueezed2.shape}")

Previous Tensor:tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous Shape:torch.Size([1, 9])

New Tensor: tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]])

New Shape: torch.Size([1, 1, 9])


In [280]:
# torch.permute - rearrange the dimensons of a target tensor in a specific order
x = torch.randn(2, 3, 6)
x.size()


torch.Size([2, 3, 6])

In [281]:
torch.permute(x, (2, 0, 1)).size()

torch.Size([6, 2, 3])

In [282]:
x_original = torch.rand(size=(224, 224, 3)) # height, width, colour_channels

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous Shape: {x_original.shape}")
print(f"New Shape: {x_permuted.shape}") # colour_channels, height, width

Previous Shape: torch.Size([224, 224, 3])
New Shape: torch.Size([3, 224, 224])


## Reproducability

### To reduce the randomness in neural networks and PyTorch comes the concept of **random seed**.
### Essentially what the random seed does is "flavour" of randomness.

In [283]:
torch.rand(3,3)

tensor([[0.8888, 0.3133, 0.9812],
        [0.3694, 0.4112, 0.8153],
        [0.1825, 0.6479, 0.6554]])

In [284]:
import torch

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.3995, 0.0776, 0.9558, 0.9176],
        [0.3159, 0.0600, 0.2781, 0.9143],
        [0.2802, 0.6020, 0.4568, 0.9710]])
tensor([[0.6964, 0.1144, 0.9052, 0.1954],
        [0.6024, 0.6438, 0.6203, 0.0910],
        [0.1027, 0.2097, 0.5187, 0.0216]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [285]:
## Random but reproducible tensors

import torch

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(4, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(4, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running Tensors and PyTorch Objects on the GPUs