In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.11.0+cu128


### Introduction To Tensors
#### Creating Tensors

In [2]:
# scaler
scalar = torch.tensor(16)
scalar

tensor(16)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

16

In [5]:
# Vector
vector = torch.tensor([16, 16])
vector

tensor([16, 16])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
 # MATRIX
 MATRIX = torch.tensor([[7, 8],
                        [9, 10]])
 MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
TENSOR2 = torch.tensor ([[[[[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9],
               [10, 11, 12]]]]]])
TENSOR2

tensor([[[[[[ 1,  2,  3],
            [ 4,  5,  6],
            [ 7,  8,  9],
            [10, 11, 12]]]]]])

In [18]:
TENSOR2.ndim

6

In [19]:
TENSOR2.shape

torch.Size([1, 1, 1, 1, 4, 3])

In [20]:
TENSOR2[0]

tensor([[[[[ 1,  2,  3],
           [ 4,  5,  6],
           [ 7,  8,  9],
           [10, 11, 12]]]]])

In [21]:
TENSOR3 = torch.tensor ([[[[[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9],
               [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18],
                [19, 20, 21],
                [22,23, 24]]]]]])
TENSOR3

tensor([[[[[[ 1,  2,  3],
            [ 4,  5,  6],
            [ 7,  8,  9],
            [10, 11, 12]],

           [[13, 14, 15],
            [16, 17, 18],
            [19, 20, 21],
            [22, 23, 24]]]]]])

In [22]:
TENSOR3.ndim

6

In [23]:
TENSOR.shape

torch.Size([1, 3, 3])

In [24]:
TENSOR3[0]

tensor([[[[[ 1,  2,  3],
           [ 4,  5,  6],
           [ 7,  8,  9],
           [10, 11, 12]],

          [[13, 14, 15],
           [16, 17, 18],
           [19, 20, 21],
           [22, 23, 24]]]]])

In [25]:
TENSOR4 = torch.tensor ([[[[[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9],
               [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18],
                [19, 20, 21],
                [22,23, 24]],
                [[31,32, 33],
               [34, 35, 36],
               [37, 38, 39],
               [103, 113, 123]],
               [[136, 146, 156],
                [166, 176, 186],
                [196, 206, 216],
                [226,236, 246]]]]]])
TENSOR4

tensor([[[[[[  1,   2,   3],
            [  4,   5,   6],
            [  7,   8,   9],
            [ 10,  11,  12]],

           [[ 13,  14,  15],
            [ 16,  17,  18],
            [ 19,  20,  21],
            [ 22,  23,  24]],

           [[ 31,  32,  33],
            [ 34,  35,  36],
            [ 37,  38,  39],
            [103, 113, 123]],

           [[136, 146, 156],
            [166, 176, 186],
            [196, 206, 216],
            [226, 236, 246]]]]]])

In [26]:
TENSOR4.ndim

6

In [27]:
TENSOR4.shape

torch.Size([1, 1, 1, 4, 4, 3])

In [28]:
TENSOR4[0]

tensor([[[[[  1,   2,   3],
           [  4,   5,   6],
           [  7,   8,   9],
           [ 10,  11,  12]],

          [[ 13,  14,  15],
           [ 16,  17,  18],
           [ 19,  20,  21],
           [ 22,  23,  24]],

          [[ 31,  32,  33],
           [ 34,  35,  36],
           [ 37,  38,  39],
           [103, 113, 123]],

          [[136, 146, 156],
           [166, 176, 186],
           [196, 206, 216],
           [226, 236, 246]]]]])

In [29]:
TENSOR5 = torch.tensor ([[[[[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9],
               [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18],
                [19, 20, 21],
                [22,23, 24]],
                [[31,32, 33],
               [34, 35, 36],
               [37, 38, 39],
               [103, 113, 123]],
               [[136, 146, 156],
                [166, 176, 186],
                [196, 206, 216],
                [226,236, 246]],
                [[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9],
               [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18],
                [19, 20, 21],
                [22,23, 24]],
                [[31,32, 33],
               [34, 35, 36],
               [37, 38, 39],
               [103, 113, 123]],
               [[136, 146, 156],
                [166, 176, 186],
                [196, 206, 216],
                [226,236, 246]]]]]])
TENSOR5

tensor([[[[[[  1,   2,   3],
            [  4,   5,   6],
            [  7,   8,   9],
            [ 10,  11,  12]],

           [[ 13,  14,  15],
            [ 16,  17,  18],
            [ 19,  20,  21],
            [ 22,  23,  24]],

           [[ 31,  32,  33],
            [ 34,  35,  36],
            [ 37,  38,  39],
            [103, 113, 123]],

           [[136, 146, 156],
            [166, 176, 186],
            [196, 206, 216],
            [226, 236, 246]],

           [[  1,   2,   3],
            [  4,   5,   6],
            [  7,   8,   9],
            [ 10,  11,  12]],

           [[ 13,  14,  15],
            [ 16,  17,  18],
            [ 19,  20,  21],
            [ 22,  23,  24]],

           [[ 31,  32,  33],
            [ 34,  35,  36],
            [ 37,  38,  39],
            [103, 113, 123]],

           [[136, 146, 156],
            [166, 176, 186],
            [196, 206, 216],
            [226, 236, 246]]]]]])

In [30]:
TENSOR5.ndim

6

In [31]:
TENSOR5.shape

torch.Size([1, 1, 1, 8, 4, 3])

In [32]:
TENSOR5[0]

tensor([[[[[  1,   2,   3],
           [  4,   5,   6],
           [  7,   8,   9],
           [ 10,  11,  12]],

          [[ 13,  14,  15],
           [ 16,  17,  18],
           [ 19,  20,  21],
           [ 22,  23,  24]],

          [[ 31,  32,  33],
           [ 34,  35,  36],
           [ 37,  38,  39],
           [103, 113, 123]],

          [[136, 146, 156],
           [166, 176, 186],
           [196, 206, 216],
           [226, 236, 246]],

          [[  1,   2,   3],
           [  4,   5,   6],
           [  7,   8,   9],
           [ 10,  11,  12]],

          [[ 13,  14,  15],
           [ 16,  17,  18],
           [ 19,  20,  21],
           [ 22,  23,  24]],

          [[ 31,  32,  33],
           [ 34,  35,  36],
           [ 37,  38,  39],
           [103, 113, 123]],

          [[136, 146, 156],
           [166, 176, 186],
           [196, 206, 216],
           [226, 236, 246]]]]])

In [33]:
# Create a random tensor of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.0526, 0.3733, 0.4507, 0.4426],
        [0.1254, 0.1011, 0.0752, 0.2123],
        [0.8940, 0.8484, 0.5427, 0.4888]])

In [34]:
random_tensor.ndim

2

In [35]:
random_tensor2 = torch.rand(1, 1, 8, 4, 3)
random_tensor2

tensor([[[[[0.1277, 0.7411, 0.0651],
           [0.1615, 0.8552, 0.6730],
           [0.6187, 0.3625, 0.4426],
           [0.8131, 0.4134, 0.0736]],

          [[0.2034, 0.4793, 0.6705],
           [0.9573, 0.7292, 0.9901],
           [0.0172, 0.4338, 0.4064],
           [0.4083, 0.8019, 0.8579]],

          [[0.5582, 0.8997, 0.3989],
           [0.8070, 0.0277, 0.8026],
           [0.6278, 0.7798, 0.3243],
           [0.3130, 0.1012, 0.6121]],

          [[0.1032, 0.6411, 0.9773],
           [0.5693, 0.7368, 0.0775],
           [0.9978, 0.5104, 0.6333],
           [0.7888, 0.2778, 0.8886]],

          [[0.8771, 0.2844, 0.5938],
           [0.6498, 0.3051, 0.3590],
           [0.9467, 0.4061, 0.8216],
           [0.5004, 0.9502, 0.9754]],

          [[0.2096, 0.4722, 0.0760],
           [0.3697, 0.8559, 0.2991],
           [0.8786, 0.3506, 0.8040],
           [0.1755, 0.5569, 0.9280]],

          [[0.2812, 0.6407, 0.6944],
           [0.2153, 0.4141, 0.6784],
           [0.6611, 0.1574

In [36]:
random_tensor2.ndim

5

In [37]:
random_tensor2.shape

torch.Size([1, 1, 8, 4, 3])

In [38]:
random_tensor2[0]

tensor([[[[0.1277, 0.7411, 0.0651],
          [0.1615, 0.8552, 0.6730],
          [0.6187, 0.3625, 0.4426],
          [0.8131, 0.4134, 0.0736]],

         [[0.2034, 0.4793, 0.6705],
          [0.9573, 0.7292, 0.9901],
          [0.0172, 0.4338, 0.4064],
          [0.4083, 0.8019, 0.8579]],

         [[0.5582, 0.8997, 0.3989],
          [0.8070, 0.0277, 0.8026],
          [0.6278, 0.7798, 0.3243],
          [0.3130, 0.1012, 0.6121]],

         [[0.1032, 0.6411, 0.9773],
          [0.5693, 0.7368, 0.0775],
          [0.9978, 0.5104, 0.6333],
          [0.7888, 0.2778, 0.8886]],

         [[0.8771, 0.2844, 0.5938],
          [0.6498, 0.3051, 0.3590],
          [0.9467, 0.4061, 0.8216],
          [0.5004, 0.9502, 0.9754]],

         [[0.2096, 0.4722, 0.0760],
          [0.3697, 0.8559, 0.2991],
          [0.8786, 0.3506, 0.8040],
          [0.1755, 0.5569, 0.9280]],

         [[0.2812, 0.6407, 0.6944],
          [0.2153, 0.4141, 0.6784],
          [0.6611, 0.1574, 0.4946],
          [0.125

In [39]:
random_tensor3 = torch.rand(3, 2, 8, 4, 3)
random_tensor3

tensor([[[[[9.6871e-01, 3.0249e-01, 1.1823e-01],
           [4.4766e-01, 8.4973e-01, 8.8643e-01],
           [5.0057e-01, 3.2577e-01, 5.7681e-01],
           [5.4979e-01, 1.4647e-01, 1.2410e-01]],

          [[1.4124e-01, 1.0133e-01, 5.6637e-01],
           [3.0613e-01, 2.0793e-01, 5.6858e-01],
           [7.6704e-01, 9.2378e-01, 4.3069e-01],
           [3.6675e-01, 8.2097e-01, 2.2257e-01]],

          [[9.5707e-01, 1.4820e-01, 9.1683e-01],
           [1.3227e-01, 6.7113e-01, 6.7479e-01],
           [3.6238e-01, 3.2250e-01, 3.4817e-02],
           [4.6881e-01, 1.4596e-01, 1.9419e-01]],

          [[3.8597e-01, 8.0293e-01, 2.0429e-01],
           [8.1479e-01, 9.3620e-01, 3.7236e-01],
           [8.4379e-01, 2.4684e-01, 4.7215e-01],
           [8.1636e-01, 8.9397e-01, 9.6561e-01]],

          [[2.6999e-01, 7.6219e-01, 9.0981e-01],
           [3.0037e-01, 9.6843e-01, 5.7241e-01],
           [8.0110e-01, 7.7153e-01, 2.3032e-01],
           [5.4262e-02, 7.0324e-01, 5.0342e-01]],

          

In [40]:
random_tensor3.ndim

5

In [41]:
random_tensor3[2]

tensor([[[[8.6533e-01, 7.4968e-01, 9.4633e-01],
          [8.9199e-01, 2.7763e-02, 9.0404e-01],
          [3.6615e-01, 4.5563e-01, 1.1377e-01],
          [8.5497e-01, 4.0447e-01, 7.8218e-01]],

         [[9.8826e-02, 9.2669e-01, 1.4544e-01],
          [5.7483e-01, 3.3432e-02, 1.8876e-01],
          [9.7174e-02, 8.1679e-01, 7.1606e-01],
          [9.8779e-01, 4.9180e-01, 9.2118e-01]],

         [[5.1992e-01, 6.4131e-01, 3.9755e-01],
          [6.2061e-01, 1.2746e-01, 8.7518e-01],
          [4.0087e-01, 2.6454e-02, 5.7279e-01],
          [9.5667e-01, 6.6150e-01, 8.2766e-01]],

         [[4.4704e-01, 1.8062e-01, 8.4343e-01],
          [2.2268e-02, 7.8175e-02, 8.5511e-01],
          [5.1726e-01, 5.8283e-01, 1.2717e-01],
          [1.8336e-01, 1.5959e-01, 6.1506e-01]],

         [[8.0265e-01, 3.3801e-01, 9.8397e-01],
          [7.6906e-01, 9.0074e-01, 9.3853e-01],
          [9.8681e-01, 6.1940e-01, 6.1111e-01],
          [3.5012e-01, 2.3849e-02, 9.9181e-01]],

         [[1.8662e-02, 1.4483e

In [42]:
# Creayte a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size= (256, 256, 3)) # height, width, colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([256, 256, 3]), 3)

In [43]:
image_shape_tensor = torch.rand(size= (3, 256, 256)) # colour channel, height, width
image_shape_tensor

tensor([[[9.0179e-01, 4.2657e-01, 8.5448e-02,  ..., 2.7083e-01,
          4.4434e-01, 9.1535e-01],
         [1.7334e-01, 9.6325e-01, 5.1692e-01,  ..., 7.7437e-01,
          5.2462e-01, 4.4215e-01],
         [5.9708e-02, 9.4112e-01, 2.0651e-01,  ..., 3.1808e-01,
          7.3625e-01, 2.0391e-01],
         ...,
         [7.1257e-01, 1.0606e-01, 7.8855e-01,  ..., 9.5693e-01,
          8.4941e-01, 2.0554e-01],
         [8.4985e-01, 5.6277e-01, 5.1255e-01,  ..., 7.8982e-01,
          5.9952e-01, 6.3602e-01],
         [9.6695e-01, 6.1503e-01, 1.8746e-01,  ..., 6.2950e-01,
          2.7629e-01, 3.5382e-01]],

        [[9.1404e-04, 1.1320e-01, 7.0687e-01,  ..., 4.0731e-01,
          4.1316e-01, 4.3153e-01],
         [6.1148e-01, 9.2375e-02, 8.6267e-01,  ..., 1.7345e-01,
          4.1472e-01, 1.2173e-01],
         [7.9910e-01, 1.3424e-01, 3.3147e-01,  ..., 4.4656e-01,
          7.5786e-01, 7.2488e-01],
         ...,
         [4.4894e-01, 7.2545e-01, 3.7827e-01,  ..., 2.8582e-01,
          3.987

In [44]:
image_shape_tensor.shape, image_shape_tensor.ndim

(torch.Size([3, 256, 256]), 3)

### Zeros and Ones

In [45]:
zeros = torch.zeros(size=(4, 6))
zeros

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [46]:
zeros.dtype

torch.float32

In [47]:
ones = torch.ones(size=(4, 6))
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [48]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [49]:
# Use torch.range()
torch.range(0,16)

/tmp/ipykernel_625/3854708265.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,16)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16.])

In [50]:
torch.arange(0, 16)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [51]:
one_to_hundred = torch.arange(start=0, end=100, step=10)
one_to_hundred

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [52]:
one_to_thousand = torch.arange(start= 2, end = 1000, step = 16)
one_to_thousand

tensor([  2,  18,  34,  50,  66,  82,  98, 114, 130, 146, 162, 178, 194, 210,
        226, 242, 258, 274, 290, 306, 322, 338, 354, 370, 386, 402, 418, 434,
        450, 466, 482, 498, 514, 530, 546, 562, 578, 594, 610, 626, 642, 658,
        674, 690, 706, 722, 738, 754, 770, 786, 802, 818, 834, 850, 866, 882,
        898, 914, 930, 946, 962, 978, 994])

In [53]:
# Creating tensors like
one_to_thousand_like = torch.zeros_like(input=one_to_thousand)
one_to_thousand_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [54]:
like_hundred = torch.ones_like(input=one_to_hundred)
like_hundred

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [55]:
like_thousand = torch.rand_like(one_to_thousand, dtype=torch.float32 )
like_thousand

tensor([0.9173, 0.4824, 0.6420, 0.8533, 0.2820, 0.6561, 0.3420, 0.7484, 0.1674,
        0.8440, 0.9240, 0.8542, 0.0135, 0.0607, 0.7670, 0.2164, 0.1664, 0.1097,
        0.1130, 0.7626, 0.0249, 0.0570, 0.3694, 0.1680, 0.0548, 0.7582, 0.7605,
        0.3928, 0.4403, 0.6968, 0.3769, 0.6438, 0.7889, 0.2815, 0.1896, 0.9661,
        0.8686, 0.0592, 0.3965, 0.4912, 0.6861, 0.9710, 0.9589, 0.4183, 0.4649,
        0.7508, 0.5206, 0.9091, 0.2871, 0.8651, 0.0203, 0.9743, 0.2876, 0.3793,
        0.8090, 0.8260, 0.7356, 0.9428, 0.5674, 0.9218, 0.3988, 0.7324, 0.4261])

In [56]:
like_hundred2 = torch.rand_like(one_to_hundred, dtype=torch.float32)
like_hundred2

tensor([0.3539, 0.6824, 0.0106, 0.9426, 0.7992, 0.9872, 0.9023, 0.8812, 0.2733,
        0.8201])

## Tensor Datatypes


In [57]:
# Float 32 tensor
# Float 32 is default datatype in PyTorch
float_32 = torch.tensor([.4, .5, .6], dtype=None)
float_32

tensor([0.4000, 0.5000, 0.6000])

In [58]:
import sys
float_32_tensor = torch.tensor([1.0, 6.0, 16.0], dtype=None)
sys.stdout.write(str(float_32_tensor) + '\n' + str(float_32_tensor.dtype)) #37 is the character count for standard output

tensor([ 1.,  6., 16.])
torch.float32

37

In [59]:
float_32_tensor = torch.tensor([1.0, 6.0, 16.0], dtype=None)
float_32_tensor.shape, float_32_tensor.ndim, float_32_tensor.dtype

(torch.Size([3]), 1, torch.float32)

In [60]:
float_32_tensor = torch.tensor([1.0, 6.0, 16.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([ 1.,  6., 16.])

In [61]:
float_16_tensor = torch.tensor([1.0, 6.0, 16.0],
                               dtype=torch.float16,
                               device=None,
                               requires_grad=False)
float_16_tensor

tensor([ 1.,  6., 16.], dtype=torch.float16)

In [62]:
float_16_tensor.dtype

torch.float16

In [63]:
float_16_tensor = torch.tensor([1.0, 6.0, 16.0],
                               dtype=torch.float16,
                               device="cpu",
                               requires_grad=False)
float_16_tensor.device

device(type='cpu')

In [64]:
float_16_tensor2 = float_32_tensor.type(torch.float16)
float_16_tensor2.dtype

torch.float16

In [65]:
float_16_tensor * float_32_tensor

tensor([  1.,  36., 256.])

In [66]:
int_32_tensor = torch.rand([1, 3])
int_32_tensor

tensor([[0.0643, 0.5868, 0.7307]])

In [67]:
float_32_tensor * int_32_tensor

tensor([[ 0.0643,  3.5210, 11.6920]])

In [68]:
long_64_tensor = torch.tensor([1, 6, 16], dtype=torch.long)
long_64_tensor

tensor([ 1,  6, 16])

In [69]:
float_32_tensor * long_64_tensor

tensor([  1.,  36., 256.])

In [70]:
kinda_tensor = torch.rand([6,6])
print(kinda_tensor)
print(f"Kinda Tensor's datatype:{kinda_tensor.dtype}") #attribute
print(f"Kinda Tensor's shape: {kinda_tensor.shape}") #attribute
print(f"Kinda Tensor's device: {kinda_tensor.device}") #attribute
print(f"Kinda Tensors size: {kinda_tensor.size()}") #size is a function

tensor([[0.6869, 0.5863, 0.6975, 0.9520, 0.5889, 0.0730],
        [0.2016, 0.0122, 0.7609, 0.8577, 0.3954, 0.6125],
        [0.3603, 0.6256, 0.8575, 0.2457, 0.8426, 0.0174],
        [0.4017, 0.3957, 0.6655, 0.3491, 0.8749, 0.8227],
        [0.3934, 0.5003, 0.5438, 0.7986, 0.8591, 0.5401],
        [0.0372, 0.3345, 0.1273, 0.8139, 0.4151, 0.7668]])
Kinda Tensor's datatype:torch.float32
Kinda Tensor's shape: torch.Size([6, 6])
Kinda Tensor's device: cpu
Kinda Tensors size: torch.Size([6, 6])


In [71]:
device = "cuda" if torch.cuda.is_available() else "cpu"
meh_tensor = torch.rand([6,6], dtype=torch.float16, device=device)
print(meh_tensor)
print(f"Meh Tensor's datatype:{meh_tensor.dtype}") #attribute
print(f"Meh Tensor's shape: {meh_tensor.shape}") #attribute
print(f"Meh Tensor's device: {meh_tensor.device}") #attribute
print(f"Meh Tensors size: {meh_tensor.size()}") #size is a function

tensor([[0.4443, 0.8521, 0.2585, 0.0030, 0.2302, 0.4187],
        [0.7544, 0.8052, 0.8711, 0.3269, 0.2817, 0.7451],
        [0.3650, 0.3938, 0.0138, 0.0013, 0.1866, 0.4380],
        [0.6260, 0.7881, 0.0104, 0.4382, 0.7593, 0.1798],
        [0.9463, 0.4331, 0.0883, 0.3457, 0.9487, 0.7983],
        [0.4253, 0.2399, 0.7866, 0.9966, 0.2593, 0.4539]], device='cuda:0',
       dtype=torch.float16)
Meh Tensor's datatype:torch.float16
Meh Tensor's shape: torch.Size([6, 6])
Meh Tensor's device: cuda:0
Meh Tensors size: torch.Size([6, 6])


## Manipulating Tensors

In [72]:
tensor1 = torch.tensor([100, 200, 300])
tensor1 + 100

tensor([200, 300, 400])

In [73]:
tensor1 - 100

tensor([  0, 100, 200])

In [74]:
tensor1 * 100

tensor([10000, 20000, 30000])

In [75]:
tensor1 / 100

tensor([1., 2., 3.])

### PyTorch in-build functions

In [76]:
torch.add(tensor1, 100)

tensor([200, 300, 400])

In [77]:
torch.sub(tensor1, 100)

tensor([  0, 100, 200])

In [78]:
torch.mul(tensor1, 100)

tensor([10000, 20000, 30000])

In [79]:
torch.div(tensor1, 100)

tensor([1., 2., 3.])

In [80]:
# Element wise multiplication
print(tensor1, "*", tensor1)
print(f"Multiplication equals:{tensor1 * tensor1}")

tensor([100, 200, 300]) * tensor([100, 200, 300])
Multiplication equals:tensor([10000, 40000, 90000])


In [81]:
torch.matmul(tensor1, tensor1) #This is just the addition of the element wise products

tensor(140000)

## This ChatGPT chat show why the below to code shows different outcomes?
- https://chatgpt.com/share/68911a9a-a8e8-8009-bbbc-cdfece7c3167

In [82]:
%%time
value = 0
for i in range (len(tensor1)):
  value += tensor1[i] * tensor1[i]
print(value)

tensor(140000)
CPU times: user 1.31 ms, sys: 0 ns, total: 1.31 ms
Wall time: 3.52 ms


In [83]:
%%time
torch.matmul(tensor1, tensor1)

CPU times: user 264 µs, sys: 0 ns, total: 264 µs
Wall time: 1.51 ms


tensor(140000)

### One of the most common error in deep learning: shape errors (I know right!!!🙂)



#### 1. Inner Dimension must match:
* `(6,4) @ (6,4)` won't work
* `(4,6) @ (6,4)` will work
* `(6,4) @ (4,6)` will work


In [84]:
torch.matmul(torch.rand(4,6), torch.rand(6, 4))

tensor([[1.5151, 0.6315, 1.6773, 0.9303],
        [1.8465, 0.9411, 2.1827, 1.9620],
        [1.1043, 0.7113, 1.0050, 0.9673],
        [1.3404, 0.5381, 1.5842, 1.4784]])

#### 2. The resulting matrix has the shape of the **outer dimensions**:
* `(4,6) @ (6,4)` shapes -> (4,4)
* `(6,4) @ (4,6)` shapes -> (6,6)
* `(6,3) @ (3,4)` shapes -> (3,4)

In [85]:
torch.matmul(torch.rand(6, 4), torch.rand(4, 6))

tensor([[0.6440, 1.1069, 1.0418, 0.7642, 1.2845, 0.4168],
        [0.6008, 1.1145, 0.6828, 0.9839, 0.6655, 0.6876],
        [0.5581, 1.6170, 1.0494, 1.3232, 1.1678, 0.9782],
        [0.3182, 0.7151, 0.3651, 0.7571, 0.5017, 0.4626],
        [0.7087, 1.0341, 0.9842, 0.7896, 1.2974, 0.3514],
        [0.6286, 1.3146, 1.0592, 1.1261, 1.5195, 0.5810]])

In [86]:
torch.matmul(torch.rand(6, 4), torch.rand(4, 3))

tensor([[1.6267, 2.1634, 1.6065],
        [0.9109, 1.0110, 0.5407],
        [1.4947, 2.1668, 1.6646],
        [0.3544, 0.6113, 0.5620],
        [0.4802, 1.0967, 0.8521],
        [0.6577, 0.7881, 0.5113]])

### To fix our tensor shapr issues, we can manipulate the shape of one of our tensors using **Transpose**.

### A **transpose** switches the axes or dimensions of a given tensor.

In [87]:
tensorA = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
tensorB = torch. tensor([[11, 12],
                         [13, 14],
                         [15, 16]])
tensorA, tensorB

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor([[11, 12],
         [13, 14],
         [15, 16]]))

In [88]:
tensorA.T #Transpose of tensorA
tensorB.T #Tnanspose of tensorB

tensorA.T, tensorB.T

(tensor([[1, 3, 5],
         [2, 4, 6]]),
 tensor([[11, 13, 15],
         [12, 14, 16]]))

In [89]:
tensorA.shape, tensorB.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [90]:
tensorA.T.shape, tensorB.T.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [91]:
tensorA * tensorB # This is working because it is element wise multiplication

tensor([[11, 24],
        [39, 56],
        [75, 96]])

In [92]:
##torch.mm(tensorA, tensorB) <- This won't work for matrix multiplication
torch.mm(tensorA, tensorB.T) # mm = matmul

tensor([[ 35,  41,  47],
        [ 81,  95, 109],
        [127, 149, 171]])

In [93]:
torch.mm(tensorA, tensorB.T).shape  ## As of rule 2 for matrix multiplication

torch.Size([3, 3])

In [94]:
# The matrix multiplication operation works when tensorB is transposed
print(f"Original shapes: tensorA = {tensorA.shape}, tensorB = {tensorB.shape}")
print(f"New shapes: tensorA = {tensorA.shape} (same shape as above), tensorB.T = {tensorB.T.shape}")
print(f"Multiplying: {tensorA.shape} @ {tensorB.T.shape} <- inner dimensions must match")
print("Output: \n")
output = torch.mm(tensorA, tensorB.T)
print(output)
print(f"\nOutput shaper: {output.shape}")

Original shapes: tensorA = torch.Size([3, 2]), tensorB = torch.Size([3, 2])
New shapes: tensorA = torch.Size([3, 2]) (same shape as above), tensorB.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output: 

tensor([[ 35,  41,  47],
        [ 81,  95, 109],
        [127, 149, 171]])

Output shaper: torch.Size([3, 3])


## Tensor Aggregation
### Finding the min, max, mean, sum etc

In [95]:
# Create a tensor
x = torch.arange (0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [96]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [97]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [98]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()
 # WE needed to change datatype here because mean does not work on Long datatype.
 # It can only work on a tensor of floating point or a complex datatype.

(tensor(45.), tensor(45.))

In [99]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional mean and max

In [100]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [101]:
x.argmin()

tensor(0)

In [102]:
x[0]

tensor(0)

In [103]:
# Find the position in tensorthat has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs.
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [104]:
x.argmin()

tensor(0)

In [105]:
x[0]

tensor(1)

In [106]:
# Max value in tensor using argmax
x.argmax()

tensor(9)

In [107]:
y = torch.arange(-100, 1, 10)
y

tensor([-100,  -90,  -80,  -70,  -60,  -50,  -40,  -30,  -20,  -10,    0])

In [108]:
y.argmin()

tensor(0)

In [109]:
y[0]

tensor(-100)

In [110]:
y.argmax()

tensor(10)

In [111]:
y[9]

tensor(-10)

## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - Reshapes an input tensor to a defined shape.
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack).
* Squeeze - Removes all `1` dimensions from a tensor.
* Unsqueeze - Add a `1` dimension to a target tensor. * Permute - Return a view of the input with dimensions permuted (swapped) in a certain way.

In [112]:
 import torch
 x = torch.arange(1., 10.)
 x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [113]:
# Add an extra dimension
x_reshape = x.reshape(1, 9)
x_reshape, x_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [114]:
x_reshape = x.reshape(9, 1)
x_reshape, x_reshape.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [115]:
x_reshape = x.reshape(1, 9)
x_reshape

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [116]:
 y = torch.arange(1., 13.)
 y, y.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [117]:
y_reshape = y.reshape(3,4)
y_reshape, y_reshape.shape

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [118]:
# Change the view
z = y.view(1,12)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [119]:
z= y.view(12,1)
z, z.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.],
         [11.],
         [12.]]),
 torch.Size([12, 1]))

In [120]:
# Changing z changes y because the view of the tensor is the same memory as the original input
z[:, 0] = 6
z, y

(tensor([[6.],
         [6.],
         [6.],
         [6.],
         [6.],
         [6.],
         [6.],
         [6.],
         [6.],
         [6.],
         [6.],
         [6.]]),
 tensor([6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]))

In [121]:
z = y.view(3,4)
z

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])

In [122]:
 y = torch.arange(1., 13.)
 y, y.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [123]:
z = y.view(1, 12)
z

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [124]:
z [:, 0] = 6
z, y

(tensor([[ 6.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 6.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [125]:
## Stack tensors on top of each other
x_stacked = torch.stack([y, y, y, y], dim = 0) # We can't use other dimensions here because origial tensor is not compatiblr
x_stacked

tensor([[ 6.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 6.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 6.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 6.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [126]:
# But we can use 1
y_stacked = torch.stack([y, y, y, y, y, y], dim=1)
y_stacked

tensor([[ 6.,  6.,  6.,  6.,  6.,  6.],
        [ 2.,  2.,  2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.,  9.,  9.],
        [10., 10., 10., 10., 10., 10.],
        [11., 11., 11., 11., 11., 11.],
        [12., 12., 12., 12., 12., 12.]])

## Squeez and Unsqueez

In [127]:
x = torch.zeros(2,1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [128]:
y = torch.squeeze(x) # squeez removes all 1 dimensions
y.size()

torch.Size([2, 2, 2])

In [129]:
y = torch.squeeze(x, 0) # remov
y.size()

torch.Size([2, 1, 2, 1, 2])

In [130]:
y = torch.squeeze(x, 1)
y.size()

torch.Size([2, 2, 1, 2])

In [131]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous Tensor:{x_reshape}")
print(f"Previous Shape:{x_reshape.shape}")

#Remove extra Dimensions from x_reshape
x_squeezed = x_reshape.squeeze()
print(f"\nNew Tensor: {x_squeezed}")
print(f"\nNew Shape: {x_squeezed.shape}")

Previous Tensor:tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous Shape:torch.Size([1, 9])

New Tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

New Shape: torch.Size([9])


In [132]:
x_reshape

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [133]:
x_reshape.shape

torch.Size([1, 9])

In [134]:
x_reshape.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [135]:
x_reshape.squeeze().shape

torch.Size([9])

In [136]:
# torch.unsqueeze() - adds a single dimensions to a target tensor
print(f"Previous Tensor:{x_squeezed}")
print(f"Previous Shape:{x_squeezed.shape}")

#Remove extra Dimensions from x_reshape
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew Tensor: {x_unsqueezed}")
print(f"\nNew Shape: {x_unsqueezed.shape}")

Previous Tensor:tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous Shape:torch.Size([9])

New Tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

New Shape: torch.Size([1, 9])


In [137]:
# torch.unsqueeze() - adds a single dimensions to a target tensor
print(f"Previous Tensor:{x_unsqueezed}")
print(f"Previous Shape:{x_unsqueezed.shape}")

#Remove extra Dimensions from x_reshape
x_unsqueezed2 = x_unsqueezed.unsqueeze(dim=1)
print(f"\nNew Tensor: {x_unsqueezed2}")
print(f"\nNew Shape: {x_unsqueezed2.shape}")

Previous Tensor:tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous Shape:torch.Size([1, 9])

New Tensor: tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]])

New Shape: torch.Size([1, 1, 9])


In [138]:
# torch.permute - rearrange the dimensons of a target tensor in a specific order
x = torch.randn(2, 3, 6)
x.size()


torch.Size([2, 3, 6])

In [139]:
torch.permute(x, (2, 0, 1)).size()

torch.Size([6, 2, 3])

In [140]:
x_original = torch.rand(size=(224, 224, 3)) # height, width, colour_channels

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous Shape: {x_original.shape}")
print(f"New Shape: {x_permuted.shape}") # colour_channels, height, width

Previous Shape: torch.Size([224, 224, 3])
New Shape: torch.Size([3, 224, 224])


## Reproducability

### To reduce the randomness in neural networks and PyTorch comes the concept of **random seed**.
### Essentially what the random seed does is "flavour" of randomness.

In [141]:
torch.rand(3,3)

tensor([[0.8814, 0.0023, 0.5207],
        [0.1190, 0.0871, 0.1591],
        [0.6655, 0.4339, 0.0930]])

In [142]:
import torch

random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(random_tensor_A)
print(random_tensor_B)
print(random_tensor_A == random_tensor_B)


tensor([[0.9184, 0.2811, 0.4380, 0.8745],
        [0.3917, 0.4511, 0.6049, 0.9851],
        [0.0864, 0.5442, 0.6382, 0.9181]])
tensor([[0.5304, 0.7180, 0.3003, 0.0738],
        [0.4717, 0.5925, 0.2059, 0.1638],
        [0.1420, 0.8211, 0.0033, 0.8004]])
tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])


In [143]:
## Random but reproducible tensors

import torch

RANDOM_SEED = 42

torch.manual_seed(RANDOM_SEED)
random_tensor_C = torch.rand(4, 4)

torch.manual_seed(RANDOM_SEED)
random_tensor_D = torch.rand(4, 4)

print(random_tensor_C)
print(random_tensor_D)
print(random_tensor_C == random_tensor_D)

tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294]])
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936],
        [0.8694, 0.5677, 0.7411, 0.4294]])
tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])


## Running Tensors and PyTorch Objects on the GPUs

In [144]:
!nvidia-smi

Tue Sep 22 14:49:04 2026       
+-----------------------------------------------------------------------------------------+
| NVIDIA-SMI 580.82.07              Driver Version: 580.82.07      CUDA Version: 13.0     |
+-----------------------------------------+------------------------+----------------------+
| GPU  Name                 Persistence-M | Bus-Id          Disp.A | Volatile Uncorr. ECC |
| Fan  Temp   Perf          Pwr:Usage/Cap |           Memory-Usage | GPU-Util  Compute M. |
|                                         |                        |               MIG M. |
|=========================================+========================+======================|
|   0  Tesla T4                       Off |   00000000:00:04.0 Off |                    0 |
| N/A   58C    P0             26W /   70W |     123MiB /  15360MiB |      0%      Default |
|                                         |                        |                  N/A |
+-----------------------------------------+-----

In [146]:
# Check for GPU access with Pytorch

import torch
torch.cuda.is_available()

True

In [147]:
# Setup device agnostic code
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cuda'

In [148]:
# Count number of devices
torch.cuda.device_count()

1

## Putting tensors and models on the GPU

In [151]:
# Create a tensor (deafult on the CPU)
tensor = torch.tensor([4, 5, 6])

# Tensor not opn GPU
print(tensor, tensor.device)

tensor([4, 5, 6]) cpu


In [152]:
# Create a tensor (deafult on the CPU), mentioning CPU
tensor = torch.tensor([4, 5, 6], device = "cpu")

# Tensor not opn GPU
print(tensor, tensor.device)

tensor([4, 5, 6]) cpu


In [153]:
# move tensor to GPU (if available)
tensor_on_gpu = tensor.to(device)
tensor_on_gpu

tensor([4, 5, 6], device='cuda:0')

## Moving tensors back to the CPU

In [156]:
# If tensor is on GPU, can't transform it to NumPy
##  tensor_on_gpu.numpy() <- This will throw an error

In [157]:
tensor_back_on_cpu = tensor_on_gpu.cpu().numpy()
tensor_back_on_cpu

array([4, 5, 6])

In [159]:
tensor_on_gpu ## As we put it back on, the tenson on gpu remained unchanged

tensor([4, 5, 6], device='cuda:0')