In [1]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
print(torch.__version__)

2.8.0+cu126


### Introduction To Tensors
#### Creating Tensors

In [2]:
# scaler
scalar = torch.tensor(16)
scalar

tensor(16)

In [3]:
scalar.ndim

0

In [4]:
scalar.item()

16

In [5]:
# Vector
vector = torch.tensor([16, 16])
vector

tensor([16, 16])

In [6]:
vector.ndim

1

In [7]:
vector.shape

torch.Size([2])

In [8]:
 # MATRIX
 MATRIX = torch.tensor([[7, 8],
                        [9, 10]])
 MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [9]:
MATRIX.ndim

2

In [10]:
MATRIX[1]

tensor([ 9, 10])

In [11]:
MATRIX[0]

tensor([7, 8])

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [13]:
# TENSOR
TENSOR = torch.tensor([[[1, 2, 3],
                        [4, 5, 6],
                        [7, 8, 9]]])
TENSOR

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]]])

In [14]:
TENSOR.ndim

3

In [15]:
TENSOR.shape

torch.Size([1, 3, 3])

In [16]:
TENSOR[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [17]:
TENSOR2 = torch.tensor ([[[[[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9],
               [10, 11, 12]]]]]])
TENSOR2

tensor([[[[[[ 1,  2,  3],
            [ 4,  5,  6],
            [ 7,  8,  9],
            [10, 11, 12]]]]]])

In [18]:
TENSOR2.ndim

6

In [19]:
TENSOR2.shape

torch.Size([1, 1, 1, 1, 4, 3])

In [20]:
TENSOR2[0]

tensor([[[[[ 1,  2,  3],
           [ 4,  5,  6],
           [ 7,  8,  9],
           [10, 11, 12]]]]])

In [21]:
TENSOR3 = torch.tensor ([[[[[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9],
               [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18],
                [19, 20, 21],
                [22,23, 24]]]]]])
TENSOR3

tensor([[[[[[ 1,  2,  3],
            [ 4,  5,  6],
            [ 7,  8,  9],
            [10, 11, 12]],

           [[13, 14, 15],
            [16, 17, 18],
            [19, 20, 21],
            [22, 23, 24]]]]]])

In [22]:
TENSOR3.ndim

6

In [23]:
TENSOR.shape

torch.Size([1, 3, 3])

In [24]:
TENSOR3[0]

tensor([[[[[ 1,  2,  3],
           [ 4,  5,  6],
           [ 7,  8,  9],
           [10, 11, 12]],

          [[13, 14, 15],
           [16, 17, 18],
           [19, 20, 21],
           [22, 23, 24]]]]])

In [25]:
TENSOR4 = torch.tensor ([[[[[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9],
               [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18],
                [19, 20, 21],
                [22,23, 24]],
                [[31,32, 33],
               [34, 35, 36],
               [37, 38, 39],
               [103, 113, 123]],
               [[136, 146, 156],
                [166, 176, 186],
                [196, 206, 216],
                [226,236, 246]]]]]])
TENSOR4

tensor([[[[[[  1,   2,   3],
            [  4,   5,   6],
            [  7,   8,   9],
            [ 10,  11,  12]],

           [[ 13,  14,  15],
            [ 16,  17,  18],
            [ 19,  20,  21],
            [ 22,  23,  24]],

           [[ 31,  32,  33],
            [ 34,  35,  36],
            [ 37,  38,  39],
            [103, 113, 123]],

           [[136, 146, 156],
            [166, 176, 186],
            [196, 206, 216],
            [226, 236, 246]]]]]])

In [26]:
TENSOR4.ndim

6

In [27]:
TENSOR4.shape

torch.Size([1, 1, 1, 4, 4, 3])

In [28]:
TENSOR4[0]

tensor([[[[[  1,   2,   3],
           [  4,   5,   6],
           [  7,   8,   9],
           [ 10,  11,  12]],

          [[ 13,  14,  15],
           [ 16,  17,  18],
           [ 19,  20,  21],
           [ 22,  23,  24]],

          [[ 31,  32,  33],
           [ 34,  35,  36],
           [ 37,  38,  39],
           [103, 113, 123]],

          [[136, 146, 156],
           [166, 176, 186],
           [196, 206, 216],
           [226, 236, 246]]]]])

In [29]:
TENSOR5 = torch.tensor ([[[[[[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9],
               [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18],
                [19, 20, 21],
                [22,23, 24]],
                [[31,32, 33],
               [34, 35, 36],
               [37, 38, 39],
               [103, 113, 123]],
               [[136, 146, 156],
                [166, 176, 186],
                [196, 206, 216],
                [226,236, 246]],
                [[1, 2, 3],
               [4, 5, 6],
               [7, 8, 9],
               [10, 11, 12]],
               [[13, 14, 15],
                [16, 17, 18],
                [19, 20, 21],
                [22,23, 24]],
                [[31,32, 33],
               [34, 35, 36],
               [37, 38, 39],
               [103, 113, 123]],
               [[136, 146, 156],
                [166, 176, 186],
                [196, 206, 216],
                [226,236, 246]]]]]])
TENSOR5

tensor([[[[[[  1,   2,   3],
            [  4,   5,   6],
            [  7,   8,   9],
            [ 10,  11,  12]],

           [[ 13,  14,  15],
            [ 16,  17,  18],
            [ 19,  20,  21],
            [ 22,  23,  24]],

           [[ 31,  32,  33],
            [ 34,  35,  36],
            [ 37,  38,  39],
            [103, 113, 123]],

           [[136, 146, 156],
            [166, 176, 186],
            [196, 206, 216],
            [226, 236, 246]],

           [[  1,   2,   3],
            [  4,   5,   6],
            [  7,   8,   9],
            [ 10,  11,  12]],

           [[ 13,  14,  15],
            [ 16,  17,  18],
            [ 19,  20,  21],
            [ 22,  23,  24]],

           [[ 31,  32,  33],
            [ 34,  35,  36],
            [ 37,  38,  39],
            [103, 113, 123]],

           [[136, 146, 156],
            [166, 176, 186],
            [196, 206, 216],
            [226, 236, 246]]]]]])

In [30]:
TENSOR5.ndim

6

In [31]:
TENSOR5.shape

torch.Size([1, 1, 1, 8, 4, 3])

In [32]:
TENSOR5[0]

tensor([[[[[  1,   2,   3],
           [  4,   5,   6],
           [  7,   8,   9],
           [ 10,  11,  12]],

          [[ 13,  14,  15],
           [ 16,  17,  18],
           [ 19,  20,  21],
           [ 22,  23,  24]],

          [[ 31,  32,  33],
           [ 34,  35,  36],
           [ 37,  38,  39],
           [103, 113, 123]],

          [[136, 146, 156],
           [166, 176, 186],
           [196, 206, 216],
           [226, 236, 246]],

          [[  1,   2,   3],
           [  4,   5,   6],
           [  7,   8,   9],
           [ 10,  11,  12]],

          [[ 13,  14,  15],
           [ 16,  17,  18],
           [ 19,  20,  21],
           [ 22,  23,  24]],

          [[ 31,  32,  33],
           [ 34,  35,  36],
           [ 37,  38,  39],
           [103, 113, 123]],

          [[136, 146, 156],
           [166, 176, 186],
           [196, 206, 216],
           [226, 236, 246]]]]])

In [33]:
# Create a random tensor of shape (3, 4)
random_tensor = torch.rand(3, 4)
random_tensor

tensor([[0.9114, 0.5425, 0.0495, 0.2333],
        [0.5032, 0.9559, 0.6789, 0.3458],
        [0.6037, 0.7826, 0.0334, 0.1748]])

In [34]:
random_tensor.ndim

2

In [35]:
random_tensor2 = torch.rand(1, 1, 8, 4, 3)
random_tensor2

tensor([[[[[0.0572, 0.6120, 0.9556],
           [0.6705, 0.5789, 0.5381],
           [0.1339, 0.1286, 0.1310],
           [0.7714, 0.3909, 0.8980]],

          [[0.4119, 0.7476, 0.1138],
           [0.9526, 0.5570, 0.0893],
           [0.4422, 0.0335, 0.4246],
           [0.1149, 0.1193, 0.5946]],

          [[0.0762, 0.8596, 0.5016],
           [0.2606, 0.7907, 0.0301],
           [0.2407, 0.0929, 0.7692],
           [0.2041, 0.9530, 0.6810]],

          [[0.2533, 0.2533, 0.0116],
           [0.1917, 0.9207, 0.9411],
           [0.0124, 0.6552, 0.6898],
           [0.9173, 0.0781, 0.2217]],

          [[0.8979, 0.2496, 0.2716],
           [0.9987, 0.9535, 0.8604],
           [0.3132, 0.4566, 0.1593],
           [0.9808, 0.0976, 0.7763]],

          [[0.1163, 0.7388, 0.7058],
           [0.4857, 0.0687, 0.3973],
           [0.6265, 0.7908, 0.6696],
           [0.6660, 0.8189, 0.9976]],

          [[0.2106, 0.4735, 0.0035],
           [0.7699, 0.7393, 0.3077],
           [0.3440, 0.1318

In [36]:
random_tensor2.ndim

5

In [37]:
random_tensor2.shape

torch.Size([1, 1, 8, 4, 3])

In [38]:
random_tensor2[0]

tensor([[[[0.0572, 0.6120, 0.9556],
          [0.6705, 0.5789, 0.5381],
          [0.1339, 0.1286, 0.1310],
          [0.7714, 0.3909, 0.8980]],

         [[0.4119, 0.7476, 0.1138],
          [0.9526, 0.5570, 0.0893],
          [0.4422, 0.0335, 0.4246],
          [0.1149, 0.1193, 0.5946]],

         [[0.0762, 0.8596, 0.5016],
          [0.2606, 0.7907, 0.0301],
          [0.2407, 0.0929, 0.7692],
          [0.2041, 0.9530, 0.6810]],

         [[0.2533, 0.2533, 0.0116],
          [0.1917, 0.9207, 0.9411],
          [0.0124, 0.6552, 0.6898],
          [0.9173, 0.0781, 0.2217]],

         [[0.8979, 0.2496, 0.2716],
          [0.9987, 0.9535, 0.8604],
          [0.3132, 0.4566, 0.1593],
          [0.9808, 0.0976, 0.7763]],

         [[0.1163, 0.7388, 0.7058],
          [0.4857, 0.0687, 0.3973],
          [0.6265, 0.7908, 0.6696],
          [0.6660, 0.8189, 0.9976]],

         [[0.2106, 0.4735, 0.0035],
          [0.7699, 0.7393, 0.3077],
          [0.3440, 0.1318, 0.3881],
          [0.636

In [39]:
random_tensor3 = torch.rand(3, 2, 8, 4, 3)
random_tensor3

tensor([[[[[0.4596, 0.2148, 0.7536],
           [0.5950, 0.1629, 0.0141],
           [0.3612, 0.0177, 0.7779],
           [0.0992, 0.5698, 0.6940]],

          [[0.7227, 0.1727, 0.3425],
           [0.6351, 0.4928, 0.1950],
           [0.4669, 0.6745, 0.4840],
           [0.2577, 0.4747, 0.5579]],

          [[0.3740, 0.6418, 0.8720],
           [0.0213, 0.0929, 0.7274],
           [0.3041, 0.1376, 0.5894],
           [0.7563, 0.4584, 0.7870]],

          [[0.5290, 0.8041, 0.6337],
           [0.2741, 0.9238, 0.9959],
           [0.4731, 0.3960, 0.7683],
           [0.0175, 0.1380, 0.7919]],

          [[0.0759, 0.8799, 0.7234],
           [0.1756, 0.8022, 0.0045],
           [0.3950, 0.3629, 0.7250],
           [0.8728, 0.2769, 0.2351]],

          [[0.1149, 0.8438, 0.8554],
           [0.2099, 0.2692, 0.0771],
           [0.8690, 0.6997, 0.8973],
           [0.6418, 0.1306, 0.6025]],

          [[0.0178, 0.0902, 0.4645],
           [0.8071, 0.1341, 0.1839],
           [0.3224, 0.3289

In [40]:
random_tensor3.ndim

5

In [41]:
random_tensor3[2]

tensor([[[[0.2334, 0.1233, 0.8357],
          [0.2131, 0.3702, 0.3218],
          [0.0261, 0.3019, 0.3326],
          [0.8576, 0.0592, 0.0452]],

         [[0.4823, 0.6836, 0.1065],
          [0.9012, 0.6883, 0.2180],
          [0.4827, 0.5963, 0.1198],
          [0.5216, 0.8700, 0.8921]],

         [[0.8601, 0.1345, 0.1522],
          [0.8111, 0.9168, 0.8289],
          [0.4148, 0.2039, 0.3169],
          [0.4445, 0.7827, 0.4781]],

         [[0.5816, 0.4314, 0.6944],
          [0.5349, 0.2144, 0.1002],
          [0.1957, 0.3725, 0.8772],
          [0.6142, 0.9968, 0.2109]],

         [[0.0135, 0.7087, 0.6988],
          [0.6405, 0.7999, 0.6680],
          [0.5232, 0.7993, 0.1378],
          [0.7311, 0.8985, 0.1076]],

         [[0.1865, 0.3065, 0.1357],
          [0.7834, 0.7251, 0.8105],
          [0.6194, 0.3077, 0.4117],
          [0.0656, 0.8722, 0.9800]],

         [[0.4465, 0.0540, 0.6335],
          [0.3469, 0.6425, 0.5983],
          [0.0158, 0.7099, 0.3846],
          [0.792

In [42]:
# Creayte a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size= (256, 256, 3)) # height, width, colour channels
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([256, 256, 3]), 3)

In [43]:
image_shape_tensor = torch.rand(size= (3, 256, 256)) # colour channel, height, width
image_shape_tensor

tensor([[[0.3186, 0.1553, 0.7185,  ..., 0.9164, 0.0622, 0.2535],
         [0.1349, 0.0862, 0.5279,  ..., 0.7368, 0.2170, 0.5756],
         [0.7614, 0.3140, 0.0487,  ..., 0.3629, 0.5974, 0.4994],
         ...,
         [0.8473, 0.7115, 0.7257,  ..., 0.4175, 0.6991, 0.0128],
         [0.0178, 0.7767, 0.3892,  ..., 0.7053, 0.0721, 0.3779],
         [0.1867, 0.7773, 0.9300,  ..., 0.5802, 0.6362, 0.3768]],

        [[0.3796, 0.5988, 0.4661,  ..., 0.9559, 0.6837, 0.4438],
         [0.4953, 0.2141, 0.0720,  ..., 0.4030, 0.5095, 0.0058],
         [0.6690, 0.8204, 0.0817,  ..., 0.7103, 0.1743, 0.3451],
         ...,
         [0.0540, 0.2466, 0.0715,  ..., 0.5541, 0.2003, 0.7576],
         [0.7663, 0.5450, 0.7894,  ..., 0.2041, 0.0585, 0.9156],
         [0.8444, 0.0102, 0.7570,  ..., 0.2720, 0.4503, 0.3780]],

        [[0.4790, 0.5644, 0.4861,  ..., 0.0050, 0.8218, 0.3373],
         [0.4252, 0.8659, 0.5980,  ..., 0.5546, 0.0427, 0.1428],
         [0.2448, 0.1987, 0.4031,  ..., 0.9880, 0.7178, 0.

In [44]:
image_shape_tensor.shape, image_shape_tensor.ndim

(torch.Size([3, 256, 256]), 3)

### Zeros and Ones

In [45]:
zeros = torch.zeros(size=(4, 6))
zeros

tensor([[0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0.]])

In [46]:
zeros.dtype

torch.float32

In [47]:
ones = torch.ones(size=(4, 6))
ones

tensor([[1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1., 1.]])

In [48]:
ones.dtype

torch.float32

## Creating a range of tensors and tensors-like

In [49]:
# Use torch.range()
torch.range(0,16)

/tmp/ipython-input-3854708265.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  torch.range(0,16)


tensor([ 0.,  1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15., 16.])

In [50]:
torch.arange(0, 16)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [51]:
one_to_hundred = torch.arange(start=0, end=100, step=10)
one_to_hundred

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [52]:
one_to_thousand = torch.arange(start= 2, end = 1000, step = 16)
one_to_thousand

tensor([  2,  18,  34,  50,  66,  82,  98, 114, 130, 146, 162, 178, 194, 210,
        226, 242, 258, 274, 290, 306, 322, 338, 354, 370, 386, 402, 418, 434,
        450, 466, 482, 498, 514, 530, 546, 562, 578, 594, 610, 626, 642, 658,
        674, 690, 706, 722, 738, 754, 770, 786, 802, 818, 834, 850, 866, 882,
        898, 914, 930, 946, 962, 978, 994])

In [53]:
# Creating tensors like
one_to_thousand_like = torch.zeros_like(input=one_to_thousand)
one_to_thousand_like

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [54]:
like_hundred = torch.ones_like(input=one_to_hundred)
like_hundred

tensor([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [55]:
like_thousand = torch.rand_like(one_to_thousand, dtype=torch.float32 )
like_thousand

tensor([0.0720, 0.1412, 0.0251, 0.9299, 0.8199, 0.9019, 0.8144, 0.5434, 0.6557,
        0.2375, 0.7097, 0.3167, 0.8454, 0.0907, 0.6092, 0.4374, 0.5654, 0.1685,
        0.4649, 0.3360, 0.9139, 0.9196, 0.5996, 0.8288, 0.8350, 0.9322, 0.4274,
        0.0398, 0.8843, 0.8604, 0.0472, 0.9693, 0.8967, 0.7535, 0.2517, 0.9706,
        0.0488, 0.3884, 0.6895, 0.9145, 0.2514, 0.9309, 0.0292, 0.2910, 0.1288,
        0.0532, 0.9605, 0.0239, 0.8041, 0.3173, 0.2043, 0.3861, 0.6435, 0.9336,
        0.7209, 0.4294, 0.1678, 0.4118, 0.4461, 0.1158, 0.7081, 0.1424, 0.5588])

In [56]:
like_hundred2 = torch.rand_like(one_to_hundred, dtype=torch.float32)
like_hundred2

tensor([0.5223, 0.0249, 0.7037, 0.8272, 0.3951, 0.2383, 0.8184, 0.2201, 0.8225,
        0.9213])

## Tensor Datatypes


In [57]:
# Float 32 tensor
# Float 32 is default datatype in PyTorch
float_32 = torch.tensor([.4, .5, .6], dtype=None)
float_32

tensor([0.4000, 0.5000, 0.6000])

In [58]:
import sys
float_32_tensor = torch.tensor([1.0, 6.0, 16.0], dtype=None)
sys.stdout.write(str(float_32_tensor) + '\n' + str(float_32_tensor.dtype)) #37 is the character count for standard output

tensor([ 1.,  6., 16.])
torch.float32

37

In [59]:
float_32_tensor = torch.tensor([1.0, 6.0, 16.0], dtype=None)
float_32_tensor.shape, float_32_tensor.ndim, float_32_tensor.dtype

(torch.Size([3]), 1, torch.float32)

In [60]:
float_32_tensor = torch.tensor([1.0, 6.0, 16.0],
                               dtype=None,
                               device=None,
                               requires_grad=False)
float_32_tensor

tensor([ 1.,  6., 16.])

In [61]:
float_16_tensor = torch.tensor([1.0, 6.0, 16.0],
                               dtype=torch.float16,
                               device=None,
                               requires_grad=False)
float_16_tensor

tensor([ 1.,  6., 16.], dtype=torch.float16)

In [62]:
float_16_tensor.dtype

torch.float16

In [63]:
float_16_tensor = torch.tensor([1.0, 6.0, 16.0],
                               dtype=torch.float16,
                               device="cpu",
                               requires_grad=False)
float_16_tensor.device

device(type='cpu')

In [64]:
float_16_tensor2 = float_32_tensor.type(torch.float16)
float_16_tensor2.dtype

torch.float16

In [65]:
float_16_tensor * float_32_tensor

tensor([  1.,  36., 256.])

In [66]:
int_32_tensor = torch.rand([1, 3])
int_32_tensor

tensor([[0.0793, 0.5588, 0.3281]])

In [67]:
float_32_tensor * int_32_tensor

tensor([[0.0793, 3.3530, 5.2497]])

In [68]:
long_64_tensor = torch.tensor([1, 6, 16], dtype=torch.long)
long_64_tensor

tensor([ 1,  6, 16])

In [69]:
float_32_tensor * long_64_tensor

tensor([  1.,  36., 256.])

In [70]:
kinda_tensor = torch.rand([6,6])
print(kinda_tensor)
print(f"Kinda Tensor's datatype:{kinda_tensor.dtype}") #attribute
print(f"Kinda Tensor's shape: {kinda_tensor.shape}") #attribute
print(f"Kinda Tensor's device: {kinda_tensor.device}") #attribute
print(f"Kinda Tensors size: {kinda_tensor.size()}") #size is a function

tensor([[0.2595, 0.1607, 0.8682, 0.7694, 0.8747, 0.2838],
        [0.2762, 0.6977, 0.4870, 0.4565, 0.8608, 0.0140],
        [0.1588, 0.1017, 0.1643, 0.6168, 0.7901, 0.6693],
        [0.8102, 0.7581, 0.7251, 0.0782, 0.8475, 0.0926],
        [0.7143, 0.5126, 0.1469, 0.9897, 0.0681, 0.9251],
        [0.0722, 0.2044, 0.8104, 0.6446, 0.8384, 0.9773]])
Kinda Tensor's datatype:torch.float32
Kinda Tensor's shape: torch.Size([6, 6])
Kinda Tensor's device: cpu
Kinda Tensors size: torch.Size([6, 6])


In [71]:
device = "cuda" if torch.cuda.is_available() else "cpu"
meh_tensor = torch.rand([6,6], dtype=torch.float16, device=device)
print(meh_tensor)
print(f"Meh Tensor's datatype:{meh_tensor.dtype}") #attribute
print(f"Meh Tensor's shape: {meh_tensor.shape}") #attribute
print(f"Meh Tensor's device: {meh_tensor.device}") #attribute
print(f"Meh Tensors size: {meh_tensor.size()}") #size is a function

tensor([[0.5278, 0.4995, 0.1475, 0.2070, 0.3857, 0.9702],
        [0.6396, 0.8472, 0.0327, 0.8804, 0.7378, 0.0713],
        [0.8389, 0.2466, 0.7466, 0.4458, 0.4434, 0.1187],
        [0.5469, 0.0420, 0.7065, 0.7617, 0.9170, 0.7212],
        [0.0713, 0.8320, 0.1387, 0.3872, 0.0527, 0.1758],
        [0.6748, 0.3926, 0.1714, 0.3921, 0.5874, 0.9692]], dtype=torch.float16)
Meh Tensor's datatype:torch.float16
Meh Tensor's shape: torch.Size([6, 6])
Meh Tensor's device: cpu
Meh Tensors size: torch.Size([6, 6])


## Manipulating Tensors

In [72]:
tensor1 = torch.tensor([100, 200, 300])
tensor1 + 100

tensor([200, 300, 400])

In [73]:
tensor1 - 100

tensor([  0, 100, 200])

In [74]:
tensor1 * 100

tensor([10000, 20000, 30000])

In [75]:
tensor1 / 100

tensor([1., 2., 3.])

### PyTorch in-build functions

In [76]:
torch.add(tensor1, 100)

tensor([200, 300, 400])

In [77]:
torch.sub(tensor1, 100)

tensor([  0, 100, 200])

In [78]:
torch.mul(tensor1, 100)

tensor([10000, 20000, 30000])

In [79]:
torch.div(tensor1, 100)

tensor([1., 2., 3.])

In [80]:
# Element wise multiplication
print(tensor1, "*", tensor1)
print(f"Multiplication equals:{tensor1 * tensor1}")

tensor([100, 200, 300]) * tensor([100, 200, 300])
Multiplication equals:tensor([10000, 40000, 90000])


In [81]:
torch.matmul(tensor1, tensor1) #This is just the addition of the element wise products

tensor(140000)

## This ChatGPT chat show why the below to code shows different outcomes?
- https://chatgpt.com/share/68911a9a-a8e8-8009-bbbc-cdfece7c3167

In [82]:
%%time
value = 0
for i in range (len(tensor1)):
  value += tensor1[i] * tensor1[i]
print(value)

tensor(140000)
CPU times: user 787 µs, sys: 0 ns, total: 787 µs
Wall time: 836 µs


In [83]:
%%time
torch.matmul(tensor1, tensor1)

CPU times: user 37 µs, sys: 6 µs, total: 43 µs
Wall time: 47 µs


tensor(140000)

### One of the most common error in deep learning: shape errors (I know right!!!🙂)



#### 1. Inner Dimension must match:
* `(6,4) @ (6,4)` won't work
* `(4,6) @ (6,4)` will work
* `(6,4) @ (4,6)` will work


In [84]:
torch.matmul(torch.rand(4,6), torch.rand(6, 4))

tensor([[2.6523, 1.4093, 2.3760, 1.9270],
        [1.5758, 1.0703, 1.0841, 0.8042],
        [2.8284, 1.5114, 1.9316, 1.9385],
        [1.8619, 0.9381, 1.9930, 1.6237]])

#### 2. The resulting matrix has the shape of the **outer dimensions**:
* `(4,6) @ (6,4)` shapes -> (4,4)
* `(6,4) @ (4,6)` shapes -> (6,6)
* `(6,3) @ (3,4)` shapes -> (3,4)

In [85]:
torch.matmul(torch.rand(6, 4), torch.rand(4, 6))

tensor([[1.4100, 1.7688, 1.5685, 0.9697, 1.9436, 1.9098],
        [1.2854, 1.9544, 1.4780, 1.1693, 2.0398, 1.4952],
        [0.5309, 1.1616, 1.2194, 0.6934, 1.2836, 1.3085],
        [0.8155, 1.2392, 1.0798, 0.6182, 1.3610, 1.1970],
        [1.1363, 1.2187, 0.6952, 0.9237, 1.1872, 0.7580],
        [0.7813, 1.0284, 0.9305, 0.5819, 1.1275, 1.1150]])

In [86]:
torch.matmul(torch.rand(6, 4), torch.rand(4, 3))

tensor([[1.8335, 1.1219, 1.1692],
        [2.5513, 1.8879, 1.8335],
        [1.1456, 0.8683, 0.9459],
        [1.5087, 0.8446, 0.7057],
        [1.8226, 1.1000, 1.2308],
        [1.8595, 1.2453, 1.3154]])

### To fix our tensor shapr issues, we can manipulate the shape of one of our tensors using **Transpose**.

### A **transpose** switches the axes or dimensions of a given tensor.

In [87]:
tensorA = torch.tensor([[1, 2],
                        [3, 4],
                        [5, 6]])
tensorB = torch. tensor([[11, 12],
                         [13, 14],
                         [15, 16]])
tensorA, tensorB

(tensor([[1, 2],
         [3, 4],
         [5, 6]]),
 tensor([[11, 12],
         [13, 14],
         [15, 16]]))

In [88]:
tensorA.T #Transpose of tensorA
tensorB.T #Tnanspose of tensorB

tensorA.T, tensorB.T

(tensor([[1, 3, 5],
         [2, 4, 6]]),
 tensor([[11, 13, 15],
         [12, 14, 16]]))

In [89]:
tensorA.shape, tensorB.shape

(torch.Size([3, 2]), torch.Size([3, 2]))

In [90]:
tensorA.T.shape, tensorB.T.shape

(torch.Size([2, 3]), torch.Size([2, 3]))

In [91]:
tensorA * tensorB # This is working because it is element wise multiplication

tensor([[11, 24],
        [39, 56],
        [75, 96]])

In [92]:
##torch.mm(tensorA, tensorB) <- This won't work for matrix multiplication
torch.mm(tensorA, tensorB.T) # mm = matmul

tensor([[ 35,  41,  47],
        [ 81,  95, 109],
        [127, 149, 171]])

In [93]:
torch.mm(tensorA, tensorB.T).shape  ## As of rule 2 for matrix multiplication

torch.Size([3, 3])

In [94]:
# The matrix multiplication operation works when tensorB is transposed
print(f"Original shapes: tensorA = {tensorA.shape}, tensorB = {tensorB.shape}")
print(f"New shapes: tensorA = {tensorA.shape} (same shape as above), tensorB.T = {tensorB.T.shape}")
print(f"Multiplying: {tensorA.shape} @ {tensorB.T.shape} <- inner dimensions must match")
print("Output: \n")
output = torch.mm(tensorA, tensorB.T)
print(output)
print(f"\nOutput shaper: {output.shape}")

Original shapes: tensorA = torch.Size([3, 2]), tensorB = torch.Size([3, 2])
New shapes: tensorA = torch.Size([3, 2]) (same shape as above), tensorB.T = torch.Size([2, 3])
Multiplying: torch.Size([3, 2]) @ torch.Size([2, 3]) <- inner dimensions must match
Output: 

tensor([[ 35,  41,  47],
        [ 81,  95, 109],
        [127, 149, 171]])

Output shaper: torch.Size([3, 3])


## Tensor Aggregation
### Finding the min, max, mean, sum etc

In [95]:
# Create a tensor
x = torch.arange (0, 100, 10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [96]:
# Find the min
torch.min(x), x.min()

(tensor(0), tensor(0))

In [97]:
# Find the max
torch.max(x), x.max()

(tensor(90), tensor(90))

In [98]:
# Find the mean
torch.mean(x.type(torch.float32)), x.type(torch.float32).mean()
 # WE needed to change datatype here because mean does not work on Long datatype.
 # It can only work on a tensor of floating point or a complex datatype.

(tensor(45.), tensor(45.))

In [99]:
# Find the sum
torch.sum(x), x.sum()

(tensor(450), tensor(450))

## Finding the positional mean and max

In [100]:
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [101]:
x.argmin()

tensor(0)

In [102]:
x[0]

tensor(0)

In [103]:
# Find the position in tensorthat has the minimum value with argmin() -> returns index position of target tensor where the minimum value occurs.
x = torch.arange(1, 100, 10)
x

tensor([ 1, 11, 21, 31, 41, 51, 61, 71, 81, 91])

In [104]:
x.argmin()

tensor(0)

In [105]:
x[0]

tensor(1)

In [106]:
# Max value in tensor using argmax
x.argmax()

tensor(9)

In [107]:
y = torch.arange(-100, 1, 10)
y

tensor([-100,  -90,  -80,  -70,  -60,  -50,  -40,  -30,  -20,  -10,    0])

In [108]:
y.argmin()

tensor(0)

In [109]:
y[0]

tensor(-100)

In [110]:
y.argmax()

tensor(10)

In [111]:
y[9]

tensor(-10)

## Reshaping, stacking, squeezing and unsqueezing tensors
* Reshaping - Reshapes an input tensor to a defined shape.
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor.
* Stacking - combine multiple tensors on top of each other (vstack) or side by side (hstack).
* Squeeze - Removes all `1` dimensions from a tensor.
* Unsqueeze - Add a `1` dimension to a target tensor. * Permute - Return a view of the input with dimensions permuted (swapped) in a certain way.

In [112]:
 import torch
 x = torch.arange(1., 10.)
 x, x.shape

(tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.]), torch.Size([9]))

In [113]:
# Add an extra dimension
x_reshape = x.reshape(1, 9)
x_reshape, x_reshape.shape

(tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]]), torch.Size([1, 9]))

In [114]:
x_reshape = x.reshape(9, 1)
x_reshape, x_reshape.shape

(tensor([[1.],
         [2.],
         [3.],
         [4.],
         [5.],
         [6.],
         [7.],
         [8.],
         [9.]]),
 torch.Size([9, 1]))

In [115]:
x_reshape = x.reshape(1, 9)
x_reshape

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [116]:
 y = torch.arange(1., 13.)
 y, y.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [117]:
y_reshape = y.reshape(3,4)
y_reshape, y_reshape.shape

(tensor([[ 1.,  2.,  3.,  4.],
         [ 5.,  6.,  7.,  8.],
         [ 9., 10., 11., 12.]]),
 torch.Size([3, 4]))

In [118]:
# Change the view
z = y.view(1,12)
z, z.shape

(tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 torch.Size([1, 12]))

In [119]:
z= y.view(12,1)
z, z.shape

(tensor([[ 1.],
         [ 2.],
         [ 3.],
         [ 4.],
         [ 5.],
         [ 6.],
         [ 7.],
         [ 8.],
         [ 9.],
         [10.],
         [11.],
         [12.]]),
 torch.Size([12, 1]))

In [120]:
# Changing z changes y because the view of the tensor is the same memory as the original input
z[:, 0] = 6
z, y

(tensor([[6.],
         [6.],
         [6.],
         [6.],
         [6.],
         [6.],
         [6.],
         [6.],
         [6.],
         [6.],
         [6.],
         [6.]]),
 tensor([6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.]))

In [121]:
z = y.view(3,4)
z

tensor([[6., 6., 6., 6.],
        [6., 6., 6., 6.],
        [6., 6., 6., 6.]])

In [122]:
 y = torch.arange(1., 13.)
 y, y.shape

(tensor([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]),
 torch.Size([12]))

In [123]:
z = y.view(1, 12)
z

tensor([[ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [124]:
z [:, 0] = 6
z, y

(tensor([[ 6.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]]),
 tensor([ 6.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]))

In [125]:
## Stack tensors on top of each other
x_stacked = torch.stack([y, y, y, y], dim = 0) # We can't use other dimensions here because origial tensor is not compatiblr
x_stacked

tensor([[ 6.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 6.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 6.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.],
        [ 6.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12.]])

In [126]:
# But we can use 1
y_stacked = torch.stack([y, y, y, y, y, y], dim=1)
y_stacked

tensor([[ 6.,  6.,  6.,  6.,  6.,  6.],
        [ 2.,  2.,  2.,  2.,  2.,  2.],
        [ 3.,  3.,  3.,  3.,  3.,  3.],
        [ 4.,  4.,  4.,  4.,  4.,  4.],
        [ 5.,  5.,  5.,  5.,  5.,  5.],
        [ 6.,  6.,  6.,  6.,  6.,  6.],
        [ 7.,  7.,  7.,  7.,  7.,  7.],
        [ 8.,  8.,  8.,  8.,  8.,  8.],
        [ 9.,  9.,  9.,  9.,  9.,  9.],
        [10., 10., 10., 10., 10., 10.],
        [11., 11., 11., 11., 11., 11.],
        [12., 12., 12., 12., 12., 12.]])

## Squeez and Unsqueez

In [127]:
x = torch.zeros(2,1, 2, 1, 2)
x.size()

torch.Size([2, 1, 2, 1, 2])

In [128]:
y = torch.squeeze(x) # squeez removes all 1 dimensions
y.size()

torch.Size([2, 2, 2])

In [129]:
y = torch.squeeze(x, 0) # remov
y.size()

torch.Size([2, 1, 2, 1, 2])

In [130]:
y = torch.squeeze(x, 1)
y.size()

torch.Size([2, 2, 1, 2])

In [131]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous Tensor:{x_reshape}")
print(f"Previous Shape:{x_reshape.shape}")

#Remove extra Dimensions from x_reshape
x_squeezed = x_reshape.squeeze()
print(f"\nNew Tensor: {x_squeezed}")
print(f"\nNew Shape: {x_squeezed.shape}")

Previous Tensor:tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous Shape:torch.Size([1, 9])

New Tensor: tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

New Shape: torch.Size([9])


In [132]:
x_reshape

tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

In [133]:
x_reshape.shape

torch.Size([1, 9])

In [134]:
x_reshape.squeeze()

tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [135]:
x_reshape.squeeze().shape

torch.Size([9])

In [136]:
# torch.unsqueeze() - adds a single dimensions to a target tensor
print(f"Previous Tensor:{x_squeezed}")
print(f"Previous Shape:{x_squeezed.shape}")

#Remove extra Dimensions from x_reshape
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew Tensor: {x_unsqueezed}")
print(f"\nNew Shape: {x_unsqueezed.shape}")

Previous Tensor:tensor([1., 2., 3., 4., 5., 6., 7., 8., 9.])
Previous Shape:torch.Size([9])

New Tensor: tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])

New Shape: torch.Size([1, 9])


In [137]:
# torch.unsqueeze() - adds a single dimensions to a target tensor
print(f"Previous Tensor:{x_unsqueezed}")
print(f"Previous Shape:{x_unsqueezed.shape}")

#Remove extra Dimensions from x_reshape
x_unsqueezed2 = x_unsqueezed.unsqueeze(dim=1)
print(f"\nNew Tensor: {x_unsqueezed2}")
print(f"\nNew Shape: {x_unsqueezed2.shape}")

Previous Tensor:tensor([[1., 2., 3., 4., 5., 6., 7., 8., 9.]])
Previous Shape:torch.Size([1, 9])

New Tensor: tensor([[[1., 2., 3., 4., 5., 6., 7., 8., 9.]]])

New Shape: torch.Size([1, 1, 9])


In [138]:
# torch.permute - rearrange the dimensons of a target tensor in a specific order
x = torch.randn(2, 3, 6)
x.size()


torch.Size([2, 3, 6])

In [139]:
torch.permute(x, (2, 0, 1)).size()

torch.Size([6, 2, 3])

In [140]:
x_original = torch.rand(size=(224, 224, 3)) # height, width, colour_channels

# Permute the original tensor to rearrange the axis (or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous Shape: {x_original.shape}")
print(f"New Shape: {x_permuted.shape}") # colour_channels, height, width

Previous Shape: torch.Size([224, 224, 3])
New Shape: torch.Size([3, 224, 224])
